trick_tracker_basic_flip = [
	"FS Shove-It"
	"Impossible"
	"Inward Heelflip"
	"Heelflip"
	"Varial Heelflip"
	"Pop Shove-it"
	"Varial Kickflip"
	"Kickflip"
	"Hardflip"
	"Half\\_Cab\\_"
]
trick_tracker_any_flip = [
	"Impossible"
	"Double Impossible"
	"Triple Impossible"
	"Front Foot Impossible"
	"Dbl. FF Impossible"
	"Inward Heelflip"
	"360 Inward Heelflip"
	"Heelflip"
	"Double Heelflip"
	"Triple Heelflip"
	"Varial Heelflip"
	"360 Heelflip"
	"Pop Shove-it"
	"360 Shove-It"
	"540 Shove-It"
	"BS Bigspin 540"
	"FS Shove-It"
	"360 FS Shove-It"
	"540 FS Shove-It"
	"Varial Kickflip"
	"360 Flip"
	"Kickflip"
	"Double Kickflip"
	"Triple Kickflip"
	"Hardflip"
	"360 Hardflip"
	"Half\\_Cab\\_"
	"The Haymaker"
	"Varial"
	"360 Varial"
	"540 Sal Flip"
	"Pop Shove-It"
	"Sal Flip"
	"Backfoot Inward Heelflip"
	"Beni Fingerflip"
	"Bodyflip Kickflip"
	"Kickflip to Crail"
	"Kickflip to Indy"
	"Double Fingerflip"
	"Fingerflip"
	"Ollie North"
	"Fingerflip Airwalk"
	"Fastest Flick"
	"Varial McTwist"
	"Nail the Trick"
]
trick_tracker_double_flip = [
	"Double Impossible"
	"360 Shove-It"
	"Double Kickflip"
	"Double Heelflip"
	"360 Inward Heelflip"
	"360 Hardflip"
	"360 Heelflip"
	"360 Flip"
]
trick_tracker_triple_flip = [
	"Triple Impossible"
	"540 Shove-It"
	"Triple Kickflip"
	"Triple Heelflip"
]
trick_tracker_basic_grab = [
	"FS Shifty"
	"Nosegrab"
	"Tailgrab"
	"Melon"
	"Mute"
	"Indy"
	"Stalefish"
	"Benihana"
	"Madonna"
	"Airwalk"
	"Crossbone"
	"Half\\_Cab\\_"
]
trick_tracker_any_grab = [
	"Nosegrab"
	"Rocket Air"
	"Tailgrab"
	"One Foot Tailgrab"
	"Melon"
	"Method"
	"Mute"
	"Seatbelt Air"
	"Indy"
	"Stiffy"
	"Stalefish"
	"Stalefish Tweak"
	"Benihana"
	"Sacktap"
	"Madonna"
	"Judo"
	"FS Shifty"
	"BS Shifty"
	"Airwalk"
	"Christ Air"
	"Crossbone"
	"CrookedCop"
	"Half\\_Cab\\_"
	"Rocket Backflip"
	"The 900"
	"Christian Air"
	"Flamingo"
	"SaranWrap"
	"Between the Legs"
	"Indy Nosebone"
	"DelMar Indy"
	"Guitar Hero"
	"Roast Beef"
	"Metal Horns"
	"Nail The Grab"
]
trick_tracker_double_grab = [
	"Rocket Air"
	"One Foot Tailgrab"
	"Method"
	"Stiffy"
	"Seatbelt Air"
	"Christ Air"
	"Sacktap"
	"Stalefish Tweak"
]
trick_tracker_basic_grind = [
	"BS 5-0"
	"BS 5-0 Hand Drag"
	"BS 5-0 Overturn"
	"BS 50-50"
	"BS Bluntslide"
	"BS Boardslide"
	"BS Boardslide Body Varial"
	"BS Chocolate Jammy"
	"BS Crail Slide"
	"BS Crooked"
	"BS Darkslide"
	"BS Feeble"
	"BS Hurricane"
	"BS Lipslide"
	"BS NoseBluntslide"
	"BS Nosegrind"
	"BS Nosegrind 360 Flip 5-0"
	"BS Noseslide"
	"BS Noseslide Tailgrab"
	"BS One Foot Crook"
	"BS One Foot Smith"
	"BS Overcrook"
	"BS Salad"
	"BS Smith"
	"BS Tailslide"
	"BS Tailslide Backflip"
	"Double Blunt Slide"
	"FS 5-0"
	"FS 5-0 Hand Drag"
	"FS 5-0 Overturn"
	"FS 50-50"
	"FS Bluntslide"
	"FS Boardslide"
	"FS Boardslide Body Varial"
	"FS Chocolate Jammy"
	"FS Crail Slide"
	"FS Crooked"
	"FS Darkslide"
	"FS Feeble"
	"FS Hurricane"
	"FS Lipslide"
	"FS NoseBluntslide"
	"FS Nosegrind"
	"FS Nosegrind 360 Flip 5-0"
	"FS Noseslide"
	"FS Noseslide Tailgrab"
	"FS One Foot Crook"
	"FS One Foot Smith"
	"FS Overcrook"
	"FS Salad"
	"FS Smith"
	"FS Tailslide"
	"FS Tailslide Backflip"
	"Hang Ten Nosegrind"
	"Nosegrind to Pivot"
]
trick_tracker_doubletap_grind = [
	"FS Crail Slide"
	"BS Crail Slide"
	"FS Darkslide"
	"BS Darkslide"
	"Double Blunt Slide"
	"FS 5-0 Overturn"
	"BS 5-0 Overturn"
	"Hang Ten Nosegrind"
	"BS Hurricane"
	"FS Hurricane"
	"Nosegrind to pivot"
	"FS Salad"
	"BS Salad"
]
trick_tracker_any_grind = [
	"BS 5-0"
	"BS 5-0 Hand Drag"
	"BS 5-0 Overturn"
	"BS 50-50"
	"BS Bluntslide"
	"BS Boardslide"
	"BS Boardslide Body Varial"
	"BS Chocolate Jammy"
	"BS Crail Slide"
	"BS Crooked"
	"BS Darkslide"
	"BS Feeble"
	"BS Hurricane"
	"BS Lipslide"
	"BS NoseBluntslide"
	"BS Nosegrind"
	"BS Nosegrind 360 Flip 5-0"
	"BS Noseslide"
	"BS Noseslide Tailgrab"
	"BS One Foot Crook"
	"BS One Foot Smith"
	"BS Overcrook"
	"BS Salad"
	"BS Smith"
	"BS Tailslide"
	"BS Tailslide Backflip"
	"Double Blunt Slide"
	"FS 5-0"
	"FS 5-0 Hand Drag"
	"FS 5-0 Overturn"
	"FS 50-50"
	"FS Bluntslide"
	"FS Boardslide"
	"FS Boardslide Body Varial"
	"FS Chocolate Jammy"
	"FS Crail Slide"
	"FS Crooked"
	"FS Darkslide"
	"FS Feeble"
	"FS Hurricane"
	"FS Lipslide"
	"FS NoseBluntslide"
	"FS Nosegrind"
	"FS Nosegrind 360 Flip 5-0"
	"FS Noseslide"
	"FS Noseslide Tailgrab"
	"FS One Foot Crook"
	"FS One Foot Smith"
	"FS Overcrook"
	"FS Salad"
	"FS Smith"
	"FS Tailslide"
	"FS Tailslide Backflip"
	"Hang Ten Nosegrind"
	"Nosegrind to Pivot"
	"BS Crossfoot Boardslide"
	"FS Crossfoot Boardslide"
	"BS Tailblock Slide"
	"FS Tailblock Slide"
	"BS Coffin Grind"
	"FS Coffin Grind"
	"BS Boardslide Hand Drag"
	"FS Boardslide Hand Drag"
]
trick_tracker_slash_grind = [
	"Slash Grind 50-50"
	"Slash Grind Boardslide"
	"Slash Grind FS Boardslide"
]
trick_tracker_slide = [
	"BS Boardslide"
	"FS Boardslide"
	"BS Lipslide"
	"FS Lipslide"
	"BS Darkslide"
	"FS Darkslide"
	"BS Noseslide"
	"FS Noseslide"
	"BS Tailslide"
	"FS Tailslide"
	"BS Bluntslide"
	"FS Bluntslide"
	"BS Nosebluntslide"
	"FS Nosebluntslide"
	"BS Crail Slide"
	"FS Crail Slide"
	"Double Blunt Slide"
]
trick_tracker_basic_lip = [
	"Axle Stall"
	"Nose Stall"
	"Rail Stall"
]
trick_tracker_any_lip = [
	"Invert"
	"Andrecht"
	"Eggplant"
	"FrontSide Invert"
	"Gymnast"
	"Kickflip to Andrecht"
	"Losi"
	"OneFoot Invert"
	"SadPlant"
	"Tailbone"
]
trick_tracker_any_stall = [
	"Axle Stall"
	"Nose Stall"
	"Rail Stall"
	"BS 50-50 Stall"
	"BS Blunt Stall"
	"BS Board Stall"
	"BS Lip Stall"
	"BS Nose Stall"
	"BS Nose Stall Tailgrab"
	"BS Noseblunt Stall"
	"BS Tail Stall"
	"BS Nosegrind Stall"
	"BS 5-0 Stall"
	"BS Crooked Stall"
	"BS Feeble Stall"
	"BS Smith Stall"
	"FS 50-50 Stall"
	"FS Blunt Stall"
	"FS Board Stall"
	"FS Lip Stall"
	"FS Nose Stall"
	"FS Nose Stall Tailgrab"
	"FS Noseblunt Stall"
	"FS Tail Stall"
	"FS Nosegrind Stall"
	"FS 5-0 Stall"
	"FS Overcrook Stall"
	"FS Feeble Stall"
	"FS Smith Stall"
]
trick_tracker_stall_or_lip = [
	"Andrecht"
	"Eggplant"
	"FrontSide Invert"
	"Gymnast"
	"Kickflip to Andrecht"
	"Losi"
	"Miller Flip"
	"OneFoot Invert"
	"SadPlant"
	"Tailbone"
	"BS 50-50 Stall"
	"BS Blunt Stall"
	"BS Board Stall"
	"BS Lip Stall"
	"BS Nose Stall"
	"BS Nose Stall Tailgrab"
	"BS Noseblunt Stall"
	"BS Tail Stall"
	"FS 50-50 Stall"
	"FS Blunt Stall"
	"FS Board Stall"
	"FS Lip Stall"
	"FS Nose Stall"
	"FS Nose Stall Tailgrab"
	"FS Noseblunt Stall"
	"FS Tail Stall"
]
trick_tracker_hold_tricks = [
	"Invert"
	"Axle Stall"
	"Nose Stall"
	"Rail Stall"
	"Andrecht"
	"Eggplant"
	"FrontSide Invert"
	"Gymnast"
	"Kickflip to Andrecht"
	"Losi"
	"OneFoot Invert"
	"SadPlant"
	"Tailbone"
	"BS 50-50 Stall"
	"BS Blunt Stall"
	"BS Board Stall"
	"BS Lip Stall"
	"BS Nose Stall"
	"BS Nose Stall Tailgrab"
	"BS Noseblunt Stall"
	"BS Tail Stall"
	"FS 50-50 Stall"
	"FS Blunt Stall"
	"FS Board Stall"
	"FS Lip Stall"
	"FS Nose Stall"
	"FS Nose Stall Tailgrab"
	"FS Noseblunt Stall"
	"FS Tail Stall"
]
trick_tracker_natas_tricks = [
	"Natas Spin"
	"L Spin"
	"One Foot Spin"
	"Handstand Spin"
]
trick_tracker_basic_manual = [
	"Manual"
	"Nose Manual"
]
trick_tracker_revert = [
	"BS Revert"
	"FS Revert"
]
trick_tracker_pivot = [
	"Nose Pivot"
	"Pivot"
]
trick_tracker_wallie = [
	"Wallie"
	"Wallieplant"
	"Wallrideplant"
]
trick_tracker_wallride = [
	"FS Wallride"
	"BS Wallride"
]
trick_tracker_any_drop = [
	"Acid Drop"
	"Bank Drop"
]
trick_tracker_any_transfer = [
	"Spine Transfer"
	"Hip Transfer"
]
trick_tracker_advanced_manual = [
	"Anti Casper"
	"Casper"
	"Rail"
	"One Foot Manual"
	"One Foot Nose Manual"
	"Pogo"
	"Pogo Spin"
	"Truckstand"
	"Switch Foot Pogo"
	"Crossfoot Pogo"
	"Spacewalk"
	"360 Fingerflip"
	"Half Cab Impossible"
]
trick_tracker_any_manual = [
	"Manual"
	"Nose Manual"
	"Anti Casper"
	"Casper"
	"Rail"
	"One Foot Manual"
	"One Foot Nose Manual"
	"Pogo"
	"Pogo Spin"
	"Truckstand"
	"Switch Foot Pogo"
	"Crossfoot Pogo"
	"Spacewalk"
	"360 Fingerflip"
	"Half Cab Impossible"
	"Mosh Manual"
	"Nail The Manual"
	"Luchador"
	"No Comply Manual"
	"MCA Manual"
	"Dog Walk"
	"Russian Boneless"
	"One Foot Nosegrab Manual"
]
unsorted_wall_tricks = [
	"Wallpush"
	"Wallplant"
]
unsorted_ground_tricks = [
	'\\LBeanplant'
	'\\LBoneless'
	'\\LFastplant'
	'\\LNo Comply'
]
unsorted_manual_tricks = [
	'\\LAnti Casper Flip'
	'\\LCasper Flip'
	'\\LCrossfootPogo Flip'
	'\\LDog Walk'
	'\\LHair Flip'
	'\\LOne Foot Flip'
	'\\LOne Foot Nose Flip'
	'\\LOne Foot Nosegrab Manual'
	'\\LOne Wheeled Manual'
	'\\LOne Wheeled Nose Manual'
	'\\LRail Flip'
	'\\LRussian Boneless'
	'\\LSwitch Foot Pogo Flip'
	'\\LTruckstand Flip'
	'\\LWrap Around'
]
unsorted_air_tricks = [
	'\\L\\c4Double Fire!\\c0'
	'\\L\\c4Double Reverse Fire!\\c0'
	'\\L\\c4Fire!\\c0'
	'\\L\\c4Object Placed!\\c0'
	'\\L\\c4Quad Fire!\\c0'
	'\\L\\c4Quad Reverse Fire!\\c0'
	'\\L\\c4Reverse Fire!\\c0'
	'\\L\\c4Triple Fire!\\c0'
	'\\L\\c4Triple Reverse Fire!\\c0'
]
unsorted_lip_tricks = [
]
unsorted_grind_tricks = [
]
