configurabletricks = [
	Trick_Kickflip
	Trick_Heelflip
	Trick_PopShoveIt
	Trick_Impossible
	Trick_VarialKickflip
	Trick_VarialHeelflip
	Trick_Hardflip
	Trick_InwardHeelflip
	Trick_FSShoveIt
	Trick_FFImpossible
	Trick_Varial
	Trick_Fingerflip
	Trick_SalFlip
	Trick_OllieNorth
	Trick_Nosegrab
	Trick_Tailgrab
	Trick_Melon
	Trick_Mute
	Trick_Indy
	Trick_Stalefish
	Trick_Benihana
	Trick_Airwalk
	Trick_FSShifty
	Trick_Madonna
	Trick_Crossbone
	Trick_IndyNosebone
	Trick_SaranWrap
	Trick_The900
	Trick_QuadKickflip
	Trick_BackfootHeel
	Trick_BodyFlipKickflip
	Trick_RocketBackflip
	Trick_StevieShove
	Trick_FingerflipAirwalk
	Trick_NTTSpecial
	Trick_GuitarHero
	Trick_RoastBeef
	Trick_MetalHorns
	Trick_Flamingo
	Trick_ChristianAir
	Trick_NailTheGrab
	Trick_DogWalk
	Trick_RussianBoneless
	Trick_NosegrabManual
	Trick_MoshManual
	Trick_NTMSpecial
	Trick_LuchadorSpecial
	Trick_NoComplyManual
	Trick_MCASpecialManual
	Trick_TailblockSlide
	Trick_CrossfootBoard
	Trick_OneFootSmith
	Trick_Darkslide
	Trick_SmithtoSmith
	Trick_Nose3flipFiveO
	Trick_BoardslideBodyVarial
	Trick_TailslideBackflip
	Trick_CoffinGrind
	Trick_WaxTheRail
	Trick_BoardslideHandDrag
	Trick_Eggplant
	Trick_KFAndrecht
	Trick_Losi
	Trick_MillerFlip
	Trick_FSInvert
	Trick_ToughGuyFlip
	Trick_ToughGuyGrab
	Trick_ToughGuyManual
	Trick_ToughGuyGrind
]
