WriteToBuffer_CompressionLookupTable_8 = [
	unlocked
	names
	new_song_info
	beststars
	tr_percent100
	bestscore
	tr_stars
	percent100
	double_bass_complete
	stars
	scores
	score
	desc_id
	chosen_materials
	material1
	contents
	completed
	started
	first_time_unlocked
	encore_unlocked
	boss_unlocked
	cash_earned
	cas_mic
	cas_bass_pickups
	cas_bass_bridges
	cas_guitar_pickguards
	cas_drums
	cas_bass_head
	cas_bass_body
	cas_guitar_head
	cas_guitar_body
	cas_guitar_bridges
	cas_bass_knobs
	cas_guitar_knobs
	cas_guitar_pickups
	cas_bass_neck
	cas_guitar_neck
	cas_bass_pickguards
	cas_mic_stand
	cas_drums_highway
	cas_guitar_highway
	cas_bass_highway
	cas_bass_head_finish
	cas_drum_finish
	cas_guitar_head_finish
	cas_guitar_finish
	cas_drum_detail
	cas_bass_finish
	cas_guitar_neck_finish
	cas_bass_neck_finish
	material2
	cas_bass_body_detail
	cas_guitar_body_detail
	cas_male_acc_left
	cas_male_shoes
	cas_male_hair
	cas_male_legs
	cas_male_acc_right
	cas_male_torso
	vol
	max_size
	valid_entries
	cas_bass_head_detail
	cas_guitar_head_detail
	cas_male_facial_hair
	cas_male_acc_ears
	cas_female_shoes
	cas_female_acc_right
	cas_female_legs
	cas_female_hair
	cas_female_torso
	cas_male_acc_face
	cas_male_hat
	cas_female_acc_left
	eq
	cas_female_acc_face
	material3
	cas_female_hat
	cas_female_acc_ears
	cas_female_facial_hair
	guitar
	last_singleplayer_character
	last_h2h_characters
	last_band_characters
	cas_guitar_pickguard_finish
	globaltag_checksum
	z_tushino
	0xc6bbede2
	0x8e2598a3
	first_career_setlist
	career_using_createagig
	0x58df7841
	0x10410d00
	rs_ghmix_editing_lesson
	got_sponsored_band_t1
	career_bass_prev_total_songs
	0x2fd848d7
	load_z_donnington
	mommyslittlemonster
	0x67463d96
	rs_melody_lesson
	guitar_motion_neck_left_idle
	got_sponsored_band_t2
	0xb6d1196d
	nothingelsematters
	0xf922a835
	0xfe4f6c2c
	drum_int_lesson
	got_sponsored_band_t3
	0xc1d629fb
	first_instrument_career_drum
	0x89485cba
	unlock_cheat_gemcolor
	unlock_Cheat_PerformanceMode
	volumes
	has_prompt_drum_tutorial
	got_sponsored_band_t4
	masterofpuppets
	got_sponsored_band_t5
	career_intro_drum_complete
	0xb1bcdd74
	got_sponsored_band_t10
	0xa362dac5
	ps2_widescreen
	got_sponsored_band_t6
	0xd2bffead
	got_sponsored_band_t11
	got_sponsored_band_t7
	0x602bf98f
	0xf5e05c29
	got_sponsored_band_t12
	got_sponsored_band_t8
	0x82e76cbf
	first_setlist_drum
	0x2492abc8
	gem_set
	stone_intro
	got_sponsored_band_t9
	0x1bee3d05
	load_z_tushino
	player_bass_save
	ghm_movie_theshorteststraw
	unlock_cheat_airinstruments
	gamma_brightness
	0x6ce90d93
	visit_outfit
	hyperspeed_guitar
	drum
	0xf28d9830
	ghm_movie_intro
	career_band_stone_movie_played
	Credits
	0xd03dbc1f
	0xb51afa76
	Crowd
	att_ballpark_band
	0x858aa8a6
	0x3305bc88
	z_studio
	visit_deformation
	0x1c83f91c
	finalbandintro_transition_played_drum
	0x6b84c98a
	got_sponsored_drum_t1
	warensemble
	0x1d82c7dd
	got_sponsored_drum_t2
	lag_calibration
	brokenbeatandscarred
	0x172cc919
	got_sponsored_drum_t3
	Progression
	0xbfac713e
	0xae429b60
	comp
	thememoryremains
	load_z_soundcheck2
	unlock_cheat_blackhighway
	star_set
	career_earnings
	load_z_meadowlands
	got_sponsored_drum_t4
	autosave
	career_vocals_movies_played
	got_sponsored_drum_t5
	fx_set
	Band
	0x28b58cce
	current_difficulty
	career_drum_movies_played
	got_sponsored_drum_t6
	vocals_sp_clap_save
	got_sponsored_drum_t7
	career_credits_bass_complete
	got_sponsored_drum_t8
	purchased_profiles
	first_instrument_career_guitar
	got_sponsored_drum_t9
	advanced_techniques_lesson
	stonecoldcrazy
	aceofspades
	0x2fea2f33
	0xbe1fad35
	ghtunes_num_songs_rated
	vocals_highway_view_save
	career_guitar_movies_played
	0x879c6f94
	0x19a63b11
	evil
	player_guitar_save
	fightfirewithfire
	bass_category
	lefty_flip_p1
	0x7ac9be0a
	0x090737d6
	0x29b84234
	lefty_flip_p2
	ghm_movie_seekanddestroy
	ns_logo
	use_tilt_for_starpower_save
	z_donnington
	warinsidemyhead
	lefty_flip_p3
	0x5fb2bc58
	cheat_index20
	lefty_flip_p4
	0x82d06be8
	career_intro_vocals_complete
	att_ballpark_bass
	cheat_index21
	drum_basic_lesson
	current_song_count
	ghm_movie4
	0xa5cf24ad
	0x5c24a6ef
	cheat_index22
	got_sponsored_vocals_t1
	load_z_forum
	ghm_movie_forwhomthebelltolls
	z_stone
	cheat_index23
	unlock_cheat_starcolor
	got_sponsored_vocals_t2
	got_sponsored_drum_t10
	ghm_movie3
	cheat_index24
	has_calibrated
	versus_lesson
	got_sponsored_vocals_t3
	band_unique_id
	hitthelights
	0xc9a513ad
	blackriver
	got_sponsored_drum_t11
	dyerseve
	cheat_index25
]
