
script game_progress_set_initial_story_mode_nodeflags 
	flags = [
		{nodeflag_gamemode_multiplayer 0}
		{nodeflag_gamemode_story 1}
		{NODEFLAG_PERMANENT_PEDS 1}
		{NODEFLAG_FINAL_GOAL 0}
		{NODEFLAG_MULTIPLAYER_SKATEPARK_BARRIER 0}
		{NODEFLAG_SKATEREYE 0}
		{NODEFLAG_IN_CAP 0}
		{nodeflag_rig_tier1 0}
		{nodeflag_rig_tier2 0}
		{nodeflag_rig_tier3 0}
		{nodeflag_attack_philly 0}
		{nodeflag_attack_dc 0}
		{nodeflag_attack_balt 0}
		{nodeflag_killed_in_cutscene 1}
		{NODEFLAG_CRIB_MINIRAMP 0}
		{NODEFLAG_CRIB_BASICHALFPIPE 1}
		{NODEFLAG_CRIB_BIGHALFPIPE 0}
		{NODEFLAG_CRIB_POOL 0}
		{nodeflag_z_crib_chalk1 1}
		{nodeflag_z_crib_chalk2 1}
		{nodeflag_z_crib_chalk3 1}
		{nodeflag_z_crib_chalk4 1}
		{nodeflag_z_crib_chalk5 1}
		{nodeflag_z_monuments_toggle_unlock 0}
		{nodeflag_z_monuments_floor_1 0}
		{NODEFLAG_Z_MONUMENTS_FLOOR_2 1}
		{nodeflag_z_monuments_uber_clearage 1}
		{nodeflag_z_monuments_art_occluders 1}
		{nodeflag_z_monuments_chalk1 1}
		{nodeflag_z_monuments_chalk2 1}
		{nodeflag_z_monuments_chalk3 1}
		{nodeflag_monuments_fbi_camera_01 1}
		{nodeflag_monuments_fbi_camera_02 1}
		{nodeflag_monuments_fbi_camera_03 1}
		{nodeflag_monuments_fbi_camera_04 1}
		{nodeflag_monuments_fbi_teleport_before 1}
		{nodeflag_monuments_fbi_teleport_after 0}
		{nodeflag_monuments_rig1_sign_before 1}
		{nodeflag_monuments_rig1_sign_after 0}
		{nodeflag_monuments_rig1_banner_before_1 1}
		{nodeflag_monuments_rig1_banner_after_1 0}
		{nodeflag_monuments_rig1_banner_before_2 1}
		{nodeflag_monuments_rig1_banner_after_2 0}
		{nodeflag_monuments_rig2_signs_before_1 1}
		{nodeflag_monuments_rig2_signs_after_1 0}
		{nodeflag_monuments_rig2_signs_before_2 1}
		{nodeflag_monuments_rig2_signs_after_2 0}
		{nodeflag_monuments_rig2_signs_before_3 1}
		{nodeflag_monuments_rig2_signs_after_3 0}
		{nodeflag_monuments_rig2_signs_before_4 1}
		{nodeflag_monuments_rig2_signs_after_4 0}
		{nodeflag_monuments_rig2_signs_before_5 1}
		{nodeflag_monuments_rig2_signs_after_5 0}
		{nodeflag_monuments_rig2_signs_before_6 1}
		{nodeflag_monuments_rig2_signs_after_6 0}
		{nodeflag_monuments_rig3_artrails_before_1 1}
		{nodeflag_monuments_rig3_artrails_after_1 0}
		{nodeflag_monuments_rig3_artrails_before_2 1}
		{nodeflag_monuments_rig3_artrails_after_2 0}
		{NODEFLAG_Z_MONUMENTS_TREE_OCCLUDER 1}
		{nodeflag_z_wp_bridge_chalk1 1}
		{nodeflag_z_wp_bridge_chalk2 1}
		{nodeflag_z_wp_bridge_chalk3 1}
		{nodeflag_unlock_wp_bridge 1}
		{NODEFLAG_Z_PB_BRIDGE_UNLOCKTUGGY_PRE 0}
		{nodeflag_pb_bridge_chalk1 1}
		{nodeflag_pb_bridge_chalk2 1}
		{nodeflag_pb_bridge_chalk3 1}
		{nodeflag_pb_bridge_barge 0}
		{NODEFLAG_PB_BRIDGE_BARGE_OFF 0}
		{NODEFLAG_PB_BRIDGE_ROLL_DOOR_EVENT_PRE 1}
		{NODEFLAG_PB_BRIDGE_ROLL_DOOR_EVENT_POST 0}
		{NODEFLAG_PB_BRIDGE_INTROCAM_1 1}
		{NODEFLAG_PB_BRIDGE_INTROCAM_2 1}
		{nodeflag_pb_bridge_unlock 1}
		{NODEFLAG_PB_BRIDGE_HELP_MESSAGE_HELI 0}
		{NODEFLAG_PB_BRIDGE_PROXIM_HELI 0}
		{nodeflag_pb_bridge_heli_door_01 1}
		{nodeflag_pb_bridge_heli_door_02 1}
		{nodeflag_pb_bridge_heli_door_03 1}
		{nodeflag_pb_bridge_heli_door_04 1}
		{nodeflag_pb_bridge_heli_door_05 1}
		{nodeflag_bw_bridge_chalk1 1}
		{nodeflag_bw_bridge_chalk2 1}
		{nodeflag_bw_bridge_chalk3 1}
		{nodeflag_bw_bridge_unlock_city 1}
		{nodeflag_bw_bridge_unlock_dc 1}
		{NODEFLAG_BW_KILL_CITY_SIDE 0}
		{NODEFLAG_BW_KILL_DC_SIDE 0}
		{nodeflag_bw_bridge_unlocked 0}
		{nodeflag_bw_bridge_rak_collision 1}
		{nodeflag_z_fdr_chalk1 1}
		{nodeflag_z_fdr_chalk2 1}
		{nodeflag_z_fdr_chalk3 1}
		{nodeflag_z_fdr_attackers 0}
		{nodeflag_z_fdr_h2_incomplete 1}
		{nodeflag_z_fdr_h2_complete 0}
		{nodeflag_z_love_chalk1 1}
		{nodeflag_z_love_chalk2 1}
		{nodeflag_z_love_chalk3 1}
		{nodeflag_z_love_chalk4 1}
		{nodeflag_z_love_chalk5 1}
		{nodeflag_z_love_chalk6 1}
		{nodeflag_love_rig3_sewergrate_pre_01 1}
		{NODEFLAG_LOVE_RIG3_SEWERGRATE_POST_01 0}
		{nodeflag_love_rig3_sewergrate_pre_02 1}
		{NODEFLAG_LOVE_RIG3_SEWERGRATE_POST_02 0}
		{nodeflag_love_rig3_squaretile_00 1}
		{nodeflag_love_rig3_squaretile_01 0}
		{nodeflag_love_rig3_squaretile_02 1}
		{nodeflag_love_rig3_squaretile_03 0}
		{nodeflag_love_rig3_squaretile_04 0}
		{nodeflag_love_rig3_squaretile_06 0}
		{nodeflag_love_rig3_squaretile_07 0}
		{nodeflag_love_rig3_squaretile_08 0}
		{nodeflag_love_rig3_squaretile_09 0}
		{nodeflag_love_rig3_squaretile_10 1}
		{nodeflag_love_rig1_lightpole_01 1}
		{nodeflag_love_rig1_lightpole_02 0}
		{nodeflag_love_rig1_lightpole_03 0}
		{nodeflag_love_rig1_lightpole_04 1}
		{nodeflag_love_rig1_lightpole_05 0}
		{nodeflag_love_rig1_lightpole_06 0}
		{nodeflag_love_rig1_lightpole_07 1}
		{nodeflag_love_rig1_lightpole_08 0}
		{nodeflag_love_rig1_lightpole_09 0}
		{nodeflag_love_rig1_lightpole_10 1}
		{nodeflag_love_rig1_lightpole_11 0}
		{nodeflag_love_rig1_lightpole_12 0}
		{nodeflag_love_unlocked 0}
		{nodeflag_love_kill_plane 1}
		{nodeflag_bell_rig3_sewergrate_pre_01 1}
		{nodeflag_bell_rig3_sewergrate_pre_02 1}
		{nodeflag_bell_rig1_lightpole_01 1}
		{nodeflag_bell_rig1_lightpole_02 0}
		{NODEFLAG_BELL_RIG1_LIGHTPOLE_03 0}
		{nodeflag_bell_rig1_lightpole_04 1}
		{nodeflag_bell_rig1_lightpole_05 0}
		{nodeflag_love_rig1_lightpole_06 0}
		{nodeflag_bell_subway_lock 1}
		{NODEFLAG_BELL_SUBWAY_UNLOCKED 0}
		{nodeflag_z_museums_chalk1 1}
		{nodeflag_z_museums_chalk2 1}
		{nodeflag_z_museums_chalk3 1}
		{nodeflag_z_museums_rig_sign1_col_after 0}
		{nodeflag_z_museums_rig_sign1_after 0}
		{nodeflag_z_museums_rig_sign2_col_after 0}
		{nodeflag_z_museums_rig_sign2_after 0}
		{nodeflag_z_museums_rig_sign1_col_before 1}
		{nodeflag_z_museums_rig_sign1_before 1}
		{nodeflag_z_museums_rig_sign2_col_before 1}
		{nodeflag_z_museums_rig_sign2_before 1}
		{nodeflag_z_museums_rig_cannon1_before 1}
		{nodeflag_z_museums_rig_cannon1_after 0}
		{nodeflag_z_museums_rig_cannon2_before 1}
		{nodeflag_z_museums_rig_cannon2_after 0}
		{nodeflag_z_museums_rig_banner01_after 0}
		{nodeflag_z_museums_rig_banner01_before 1}
		{nodeflag_z_museums_rig_banner02_after 0}
		{nodeflag_z_museums_rig_banner02_before 1}
		{nodeflag_z_museums_rig_banner03_after 0}
		{nodeflag_z_museums_rig_banner03_before 1}
		{nodeflag_z_museums_rig_banner_rail_before 1}
		{nodeflag_z_museums_rig_banner_rail_after 0}
		{nodeflag_z_museum_int_chalk1 1}
		{nodeflag_z_museum_int_chalk2 1}
		{nodeflag_z_museum_int_chalk3 1}
		{NODEFLAG_UNLOCK_NASM 0}
		{nodeflag_z_museum_int_slingshot 0}
		{nodeflag_z_museum_int_triggers 1}
		{NODEFLAG_Z_MUSEUM_INT_WRIGHT_PRE 1}
		{NODEFLAG_Z_MUSEUM_INT_WRIGHT_A 0}
		{NODEFLAG_Z_MUSEUM_INT_WRIGHT_B 0}
		{NODEFLAG_Z_MUSEUM_INT_WRIGHT_FINAL 0}
		{nodeflag_z_museum_int_doors_lock 1}
		{nodeflag_z_museum_int_unlocked 0}
		{nodeflag_z_lansdowne_chalk1 1}
		{nodeflag_z_lansdowne_chalk2 1}
		{nodeflag_z_lansdowne_chalk3 1}
		{nodeflag_z_lansdowne_locked 1}
		{nodeflag_z_lansdowne_unlocked 0}
		{nodeflag_z_secret_lock 1}
		{nodeflag_z_secret_unlock 0}
		{nodeflag_z_secret_lock_wp 1}
		{nodeflag_z_secret_unlock_wp 0}
		{nodeflag_slums_rig1_car1_pre 1}
		{nodeflag_slums_rig1_car1_post 0}
		{nodeflag_slums_rig1_car2_pre 1}
		{nodeflag_slums_rig1_car2_post 0}
		{nodeflag_slums_rig1_car3_pre 1}
		{nodeflag_slums_rig1_car3_post 0}
		{nodeflag_slums_rig2_jersey1_post 0}
		{nodeflag_slums_rig2_jersey2_post 0}
		{nodeflag_slums_rig2_jersey3_post 0}
		{nodeflag_slums_rig2_jersey4_post 0}
		{nodeflag_slums_rig2_jersey5_post 0}
		{nodeflag_slums_rig3_billboard1_pre 1}
		{nodeflag_slums_rig3_billboard1_post 0}
		{nodeflag_slums_rig3_billboard2_pre 1}
		{nodeflag_slums_rig3_billboard2_post 0}
		{nodeflag_slums_rig3_billboard3_pre 1}
		{nodeflag_slums_rig3_billboard3_post 0}
		{nodeflag_slums_rig_uber_mod_triggers 0}
		{nodeflag_slums_rig_uber_propane_kicks_opt1 0}
		{nodeflag_slums_rig_uber_propane_kicks_opt2 0}
		{nodeflag_slums_rig_uber_propane_kicks_opt3 0}
		{nodeflag_slums_rig_uber_pipe_rails_opt1 0}
		{nodeflag_slums_rig_uber_pipe_rails_opt2 0}
		{nodeflag_slums_rig_uber_pipe_rails_opt3 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt1_a 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt2_a 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt3_a 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt1_b 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt2_b 0}
		{nodeflag_slums_rig_uber_wheel_boosters_opt3_b 0}
		{nodeflag_unlock_slums_love 0}
		{nodeflag_unlock_slums_fdr 0}
		{nodeflag_lock_slums_fdr 1}
		{nodeflag_slums_training_grind 0}
		{nodeflag_slums_training_manual 0}
		{nodeflag_slums_chalk3 0}
		{nodeflag_slums_chalk4 0}
		{NODEFLAG_UNLOCK_HARBOR_LANSDOWNE 0}
		{nodeflag_harbor_chalk1 1}
		{nodeflag_harbor_chalk2 1}
		{nodeflag_harbor_chalk3 1}
		{nodeflag_harbor_handrailmod_01_pre 1}
		{nodeflag_harbor_handrailmod_01_post 0}
		{nodeflag_harbor_handrailmod_02_pre 1}
		{nodeflag_harbor_handrailmod_02_post 0}
		{nodeflag_harbor_handrailmod_03_pre 1}
		{nodeflag_harbor_handrailmod_03_post 0}
		{nodeflag_harbor_scaffoldmod_01_pre 1}
		{nodeflag_harbor_scaffoldmod_01_post 0}
		{nodeflag_harbor_wtcscaffoldmod_01_pre 1}
		{nodeflag_harbor_wtcscaffoldmod_01_post 0}
		{NODEFLAG_HARBOR_STOPSIGNMOD_01_PRE 1}
		{NODEFLAG_HARBOR_STOPSIGNMOD_01_POST 0}
		{nodeflag_harbor_stopsignmod_02_pre 1}
		{nodeflag_harbor_stopsignmod_02_post 0}
		{NODEFLAG_HARBOR_PEDSIGNMOD_01_PRE 1}
		{NODEFLAG_HARBOR_PEDSIGNMOD_01_POST 0}
		{nodeflag_harbor_speedingsignmod_01_pre 1}
		{nodeflag_harbor_speedingsignmod_01_post 0}
		{nodeflag_harbor_speedingsignmod_02_pre 1}
		{nodeflag_harbor_speedingsignmod_02_post 0}
		{nodeflag_harbor_speedingsignmod_03_pre 1}
		{nodeflag_harbor_speedingsignmod_03_post 0}
		{nodeflag_harbor_speedingsignmod_04_pre 1}
		{nodeflag_harbor_speedingsignmod_04_post 0}
		{nodeflag_bcity_chalk1 1}
		{nodeflag_bcity_chalk2 1}
		{nodeflag_bcity_chalk3 1}
		{nodeflag_bcity_hopkinsrailmod_01_pre 1}
		{nodeflag_bcity_hopkinsrailmod_01_post 0}
		{nodeflag_bcity_theaterrailmod_01_pre 1}
		{nodeflag_bcity_theaterrailmod_01_post 0}
		{NODEFLAG_BCITY_WALKKICKMOD_01_PRE 1}
		{NODEFLAG_BCITY_WALKKICKMOD_01_POST 0}
		{nodeflag_bcity_citysignmod_01_pre 1}
		{nodeflag_bcity_citysignmod_01_post 0}
		{nodeflag_bcity_citysignmod_02_pre 1}
		{nodeflag_bcity_citysignmod_02_post 0}
		{nodeflag_bcity_movieposterhorror 1}
		{nodeflag_bcity_movieposterskate 0}
		{nodeflag_bcity_rooffencepoolstate_closed 1}
		{nodeflag_m_film_mod_harbor_bank01 0}
		{nodeflag_m_film_mod_harbor_bank02 0}
		{nodeflag_m_film_mod_harbor_bank01a 1}
		{nodeflag_m_film_mod_harbor_bank02a 1}
		{NODEFLAG_Z_HOUSES_UNLOCKSHOPS_PRE 1}
		{NODEFLAG_Z_HOUSES_UNLOCKSHOPS_POST 0}
		{nodeflag_z_houses_unlockcretepark_pre 0}
		{NODEFLAG_Z_HOUSES_UNLOCKCRETEPARK_POST 1}
		{NODEFLAG_Z_HOUSES_CHALK1_COMPLETE 0}
		{NODEFLAG_Z_INSCHOOL_DITCH_LOCKED 1}
		{NODEFLAG_Z_INSCHOOL_DITCH_UNLOCKED 0}
		{nodeflag_z_inschool_classroom_locked 0}
		{nodeflag_z_inschool_classroom_unlocked 1}
		{NODEFLAG_Z_GHETTO_PARK_UNLOCKED 0}
		{NODEFLAG_Z_GHETTO_PARK_LOCKED 1}
		{nodeflag_z_ghetto_secret_area_locked 0}
		{nodeflag_z_ghetto_secret_area_unlocked 1}
		{NODEFLAG_Z_GHETTO_UNLOCKFACTORY_PRE 0}
		{NODEFLAG_Z_GHETTO_UNLOCKFACTORY_POST 1}
		{NODEFLAG_Z_FACTORY_CRASHTEST_ENTER 0}
		{NODEFLAG_Z_SHOPS_UNLOCKSCHOOL_PRE 0}
		{NODEFLAG_Z_SHOPS_UNLOCKSCHOOL_POST 1}
		{NODEFLAG_Z_PARKING_UNLOCKFUNPARK_PRE 0}
		{NODEFLAG_Z_PARKING_UNLOCKFUNPARK_POST 1}
		{NODEFLAG_M_TURF_LIBRARY 1}
		{nodeflag_secret_powerplant_teleport01 1}
		{nodeflag_z_cretepark_hilltop 1}
		{nodeflag_z_cretepark_greenroof 1}
		{nodeflag_z_cretepark_trees 1}
	]
	getarraysize flags
	i = 0
	begin
	changenodeflag (<flags> [<i>])
	i = (<i> + 1)
	repeat <array_size>
	if ($all_levels_unlocked = 1)
		unlock_all_game_areas
	else
	endif
endscript

script game_progress_set_non_story_mode_nodeflags 
	game_progress_set_initial_story_mode_nodeflags
	flags = [
		{NODEFLAG_PERMANENT_PEDS 0}
		{nodeflag_gamemode_multiplayer 1}
		{nodeflag_gamemode_story 0}
		{NODEFLAG_PROS_UNLOCKED_BEFORE 1}
		{NODEFLAG_PROS_UNLOCKED_AFTER 0}
		{nodeflag_z_monuments_art_occluders 0}
		{nodeflag_z_monuments_toggle_unlock 0}
		{nodeflag_z_secret_lock_wp 1}
		{nodeflag_z_secret_unlock_wp 0}
		{nodeflag_z_museums_rig_cannon1_after 1}
		{nodeflag_z_museums_rig_cannon2_after 1}
		{nodeflag_z_museums_rig_cannon1_before 0}
		{nodeflag_z_museums_rig_cannon2_before 0}
	]
	getarraysize flags
	i = 0
	begin
	changenodeflag (<flags> [<i>])
	i = (<i> + 1)
	repeat <array_size>
	unlock_all_game_areas
endscript
