gh4_songlist = [
	dlc251
	dlc252
	dlc253
	dlc254
	dlc255
	dlc256
	dlc257
	dlc258
	dlc259
	dlc260
	dlc261
	dlc262
	dlc263
	dlc264
	dlc265
	dlc266
	dlc267
	dlc268
	dlc269
	dlc270
	dlc271
	dlc272
	dlc273
	dlc274
	dlc275
	dlc276
	dlc277
	dlc278
	dlc279
	dlc280
	dlc281
	dlc323
	dlc288
	dlc282
	dlc283
	dlc284
	dlc285
	dlc286
	dlc287
	dlc324
	dlc289
	dlc290
	dlc291
	dlc292
	dlc293
	dlc294
	dlc295
	dlc296
	dlc299
	dlc297
	dlc298
	dlc300
	dlc301
	dlc302
	dlc303
	dlc304
	dlc305
	dlc306
	dlc307
	dlc308
	dlc309
	dlc310
	dlc311
	dlc312
	dlc313
	dlc314
	dlc315
	dlc316
	dlc317
	dlc318
	dlc319
	dlc320
	dlc321
	dlc322
	dlc325
	dlc326
	dlc328
	dlc327
	dlc329
	dlc330
	dlc331
	dlc332
	dlc333
	dlc334
	dlc335
	dlc336
]
gh4_songlist_props = {
	dlc251 = {
		checksum = dlc251
		name = 'dlc251'
		title = qs(0xf4b19017)
		artist = qs(0x5a827f81)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -3.2
		duration = 184
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	dlc252 = {
		checksum = dlc252
		name = 'dlc252'
		title = qs(0x8b27c358)
		artist = qs(0x20a2d18b)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = 2.2
		duration = 190
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc253 = {
		checksum = dlc253
		name = 'dlc253'
		title = qs(0x0b7f7830)
		artist = qs(0x29d92c8a)
		year = 1970
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		mono_drums = 1
		overall_song_volume = -0.5
		duration = 246
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc254 = {
		checksum = dlc253
		name = 'dlc254'
		title = qs(0x5efe0bf1)
		artist = qs(0x216fb9d4)
		year = 1980
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		countoff = 'hihat01'
		drum_kit = 'heavyrock'
		overall_song_volume = -2.4
		vocals_scroll_speed = 1.1700001
		duration = 315
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc255 = {
		checksum = dlc255
		name = 'dlc255'
		title = qs(0x33664bfa)
		artist = qs(0xa63dbc27)
		year = 1993
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -1.2
		duration = 215
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 2
		band_difficulty_rating = 5
	}
	dlc256 = {
		checksum = dlc256
		name = 'dlc256'
		title = qs(0x398681c3)
		artist = qs(0xb1aa12ed)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2.0
		duration = 220
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 8
	}
	dlc257 = {
		checksum = dlc257
		name = 'dlc257'
		title = qs(0x3d49899b)
		artist = qs(0x12a28bfd)
		year = 1973
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2
		duration = 314
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
		vocals_pitch_score_shift = {
			cents = 4
		}
	}
	dlc258 = {
		checksum = dlc258
		name = 'dlc258'
		title = qs(0x359536e1)
		artist = qs(0xb17f2906)
		year = 1982
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = pop
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -2.4
		duration = 278
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 1
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc259 = {
		checksum = dlc259
		name = 'dlc259'
		title = qs(0xe99595d8)
		artist = qs(0xcd4bcb98)
		year = 1997
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -1.9
		duration = 241
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
	}
	dlc260 = {
		checksum = dlc260
		name = 'dlc260'
		title = qs(0xebdd2712)
		artist = qs(0xf25755cf)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = none
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		boss = boss_ted_props
		allowed_in_quickplay = 0
		overall_song_volume = 3.8
		duration = 201
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc261 = {
		checksum = dlc261
		name = 'dlc261'
		title = qs(0xd474ea1f)
		artist = qs(0x98fdbfd6)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = none
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		boss = boss_zakk_props
		allowed_in_quickplay = 0
		overall_song_volume = 1.2
		duration = 221
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 3
		band_difficulty_rating = 6
	}
	dlc262 = {
		checksum = dlc262
		name = 'dlc262'
		title = qs(0xf830db62)
		artist = qs(0x9d15841f)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `nu metal`
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -3
		vocals_scroll_speed = 1.2
		duration = 261
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 10
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 8
		band_difficulty_rating = 8
	}
	dlc263 = {
		checksum = dlc263
		name = 'dlc263'
		title = qs(0x75fd4f6a)
		artist = qs(0x7878e4e7)
		year = 1980
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = metal
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		drum_solo = 1
		overall_song_volume = -4.2
		duration = 303
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 7
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 180
	}
	dlc264 = {
		checksum = dlc264
		name = 'dlc264'
		title = qs(0xe8ca878e)
		artist = qs(0xf46ae5b0)
		year = 1997
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `pop punk`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -3.4
		duration = 173
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
	}
	dlc265 = {
		checksum = dlc265
		name = 'dlc265'
		title = qs(0xc92e3a4b)
		artist = qs(0xb254a71a)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		performance = 1
		overall_song_volume = -2.2
		duration = 254
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
	}
	dlc266 = {
		checksum = dlc266
		name = 'dlc266'
		title = qs(0x899aee8a)
		artist = qs(0x504043ab)
		year = 1972
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -3
		duration = 366
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	dlc267 = {
		checksum = dlc267
		name = 'dlc267'
		title = qs(0xbb8fa510)
		artist = qs(0x693076a1)
		year = 1984
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = punk
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2
		duration = 217
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 9
		band_difficulty_rating = 6
	}
	dlc268 = {
		checksum = dlc268
		name = 'dlc268'
		title = qs(0xdb32b349)
		artist = qs(0xcb5e8a23)
		year = 1997
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2.4
		duration = 261
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
	}
	dlc269 = {
		checksum = dlc269
		name = 'dlc269'
		title = qs(0x0ed97f3e)
		artist = qs(0x80beb9a7)
		year = 1982
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_huge'
		drum_kit = 'heavyrock'
		drum_solo = 1
		overall_song_volume = -2.9
		duration = 260
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	dlc270 = {
		checksum = dlc270
		name = 'dlc270'
		title = qs(0x2cbb6876)
		artist = qs(0x09357ea5)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `indie rock`
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -2
		duration = 263
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	dlc271 = {
		checksum = dlc271
		name = 'dlc271'
		title = qs(0xf8cdd2f3)
		artist = qs(0x1ced2a37)
		year = 2004
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `indie rock`
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -2.6
		vocals_scroll_speed = 1.25
		duration = 212
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	dlc272 = {
		checksum = dlc272
		name = 'dlc272'
		title = qs(0x7c376e75)
		artist = qs(0x8ec08439)
		year = 1998
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `nu metal`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -1.6
		duration = 274
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	dlc273 = {
		checksum = dlc273
		name = 'dlc273'
		title = qs(0x52ad2897)
		artist = qs(0x8180a7a3)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = pop
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2
		duration = 168
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 10
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		vocals_scroll_speed = 1.05
	}
	dlc274 = {
		checksum = dlc274
		name = 'dlc274'
		title = qs(0x4175cf29)
		artist = qs(0x92d10fee)
		year = 1977
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2
		duration = 244
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		vocals_pitch_score_shift = {
			cents = 18
		}
	}
	dlc275 = {
		checksum = dlc275
		name = 'dlc275'
		title = qs(0x1717eeb9)
		artist = qs(0x162385e5)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = -2.5
		duration = 189
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
	}
	dlc276 = {
		checksum = dlc276
		name = 'dlc276'
		title = qs(0x343e4db8)
		artist = qs(0xedbd7c29)
		year = 1979
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = rock
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = -2.5
		duration = 213
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 120
	}
	dlc277 = {
		checksum = dlc277
		name = 'dlc277'
		title = qs(0xaa984ecf)
		artist = qs(0xe3d91216)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'hihat01'
		drum_kit = 'heavyrock'
		overall_song_volume = -1.1
		duration = 306
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc278 = {
		checksum = dlc278
		name = 'dlc278'
		title = qs(0x40700c1d)
		artist = qs(0x9618326b)
		year = 1978
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = -3
		duration = 308
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
	}
	dlc279 = {
		checksum = dlc279
		name = 'dlc279'
		title = qs(0x12217b98)
		artist = qs(0x4f0cce27)
		year = 1976
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = 1.3
		duration = 405
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	dlc280 = {
		checksum = dlc280
		name = 'dlc280'
		title = qs(0xeb593a63)
		artist = qs(0x7cd3eb96)
		year = 1984
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = -1.3
		duration = 291
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 9
		drums_difficulty_rating = 9
		band_difficulty_rating = 9
		vocals_pitch_score_shift = {
			cents = 36
		}
		drum_solo = 1
		vocals_scroll_speed = 1.22
	}
	dlc281 = {
		checksum = dlc281
		name = 'dlc281'
		title = qs(0x92369909)
		artist = qs(0x2138d7b1)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -1.8
		duration = 181
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc323 = {
		checksum = dlc323
		name = 'dlc323'
		title = qs(0xefa2bacd)
		artist = qs(0x03d1c2c3)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `pop rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -1.7
		duration = 251
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
	}
	dlc288 = {
		checksum = dlc288
		name = 'dlc288'
		title = qs(0x0b1a174e)
		artist = qs(0x1c8125b5)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `prog rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = 0.7
		duration = 313
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 6
		band_difficulty_rating = 6
	}
	dlc282 = {
		checksum = dlc282
		name = 'dlc282'
		title = qs(0x0f44c507)
		artist = qs(0x078597dd)
		year = 1987
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -2.2
		duration = 139
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 7
		band_difficulty_rating = 7
		vocals_pitch_score_shift = {
			cents = 30
		}
		drum_solo = 1
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
	}
	dlc283 = {
		checksum = dlc283
		name = 'dlc283'
		title = qs(0xa4a75e17)
		artist = qs(0x3e6463ce)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `indie rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2
		duration = 366
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc284 = {
		checksum = dlc284
		name = 'dlc284'
		title = qs(0xc428b4f7)
		artist = qs(0x166b4344)
		year = 1986
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 0.3
		duration = 285
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	dlc285 = {
		checksum = dlc285
		name = 'dlc285'
		title = qs(0x71e2a43e)
		artist = qs(0x50c4360e)
		year = 1967
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		drum_solo = 1
		overall_song_volume = 0.5
		duration = 198
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
	}
	dlc286 = {
		checksum = dlc286
		name = 'dlc286'
		title = qs(0x8a884e08)
		artist = qs(0xca48fbc1)
		year = 1987
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		countoff = 'hihat01'
		drum_kit = 'heavyrock'
		overall_song_volume = -2.3
		duration = 265
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 4
		band_difficulty_rating = 6
	}
	dlc287 = {
		checksum = dlc287
		name = 'dlc287'
		title = qs(0x83aa393a)
		artist = qs(0xc2400ecd)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -3
		duration = 353
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 7
		band_difficulty_rating = 7
		vocals_pitch_score_shift = {
			cents = 15
		}
	}
	dlc324 = {
		checksum = dlc324
		name = 'dlc324'
		title = qs(0x599b87fe)
		artist = qs(0xa0c30267)
		year = 2001
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `pop punk`
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -3.5
		duration = 173
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc289 = {
		checksum = dlc289
		name = 'dlc289'
		title = qs(0xe8661dc8)
		artist = qs(0x147972ce)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `pop punk`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -1.3
		duration = 207
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 6
		band_difficulty_rating = 4
		vocals_scroll_speed = 1.1
	}
	dlc290 = {
		checksum = dlc290
		name = 'dlc290'
		title = qs(0xb9828a62)
		artist = qs(0x5d89a554)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `pop rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 1.5
		duration = 248
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	dlc291 = {
		checksum = dlc291
		name = 'dlc291'
		title = qs(0xe300a7de)
		artist = qs(0x7076a57b)
		year = 1988
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -0.8
		duration = 247
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 6
		band_difficulty_rating = 4
	}
	dlc292 = {
		checksum = dlc292
		name = 'dlc292'
		title = qs(0x4cce904d)
		artist = qs(0x7878e4e7)
		year = 1980
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = -2
		duration = 325
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 5
		band_difficulty_rating = 7
	}
	dlc293 = {
		checksum = dlc293
		name = 'dlc293'
		title = qs(0xfa306537)
		artist = qs(0x35fa521d)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `blues rock`
		countoff = 'hihat01'
		drum_kit = 'fusion'
		overall_song_volume = -1.5
		duration = 241
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc294 = {
		checksum = dlc294
		name = 'dlc294'
		title = qs(0xc0f53224)
		artist = qs(0x70cd0657)
		year = 1986
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = hip_hop
		countoff = 'sticks_normal'
		drum_kit = 'hiphop'
		overall_song_volume = -2.6
		vocals_scroll_speed = 1.3
		duration = 271
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	dlc295 = {
		checksum = dlc295
		name = 'dlc295'
		title = qs(0xb28db398)
		artist = qs(0x63aa1e3a)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -0.8
		duration = 201
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc296 = {
		checksum = dlc296
		name = 'dlc296'
		title = qs(0x0f0ed0a5)
		artist = qs(0xbbcd5420)
		year = 2002
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -0.8
		duration = 254
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
	}
	dlc299 = {
		checksum = dlc299
		name = 'dlc299'
		title = qs(0x81bae0db)
		artist = qs(0xb3ad29ec)
		year = 1980
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = country
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0.1
		duration = 161
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 1
		band_difficulty_rating = 4
	}
	dlc297 = {
		checksum = dlc297
		name = 'dlc297'
		title = qs(0x65f25a7a)
		artist = qs(0x791f4526)
		year = 2000
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2
		duration = 232
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
	}
	dlc298 = {
		checksum = dlc298
		name = 'dlc298'
		title = qs(0x62ffe213)
		artist = qs(0x3cacd574)
		year = 1978
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `new wave`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -0.8
		duration = 232
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc300 = {
		checksum = dlc300
		name = 'dlc300'
		title = qs(0x81a2e3ba)
		artist = qs(0x7b76a5bc)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `nu metal`
		double_kick = 1
		countoff = 'hihat01'
		drum_kit = 'fusion'
		overall_song_volume = -3
		duration = 245
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
	}
	dlc301 = {
		checksum = dlc301
		name = 'dlc301'
		title = qs(0xbae0f221)
		artist = qs(0xba3d637f)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = metal
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		drum_solo = 1
		overall_song_volume = -2.2
		duration = 298
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 7
		band_difficulty_rating = 6
	}
	dlc302 = {
		checksum = dlc302
		name = 'dlc302'
		title = qs(0x19f385ca)
		artist = qs(0xbb1e4a7e)
		year = 2001
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `prog rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		drum_solo = 1
		overall_song_volume = -2.3
		duration = 372
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 6
		band_difficulty_rating = 6
	}
	dlc303 = {
		checksum = dlc303
		name = 'dlc303'
		title = qs(0x4d3dee69)
		artist = qs(0x606cd8a9)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = punk
		countoff = 'sticks_huge'
		drum_kit = 'classicrock'
		overall_song_volume = -0.5
		duration = 203
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
	}
	dlc304 = {
		checksum = dlc304
		name = 'dlc304'
		title = qs(0x94859646)
		artist = qs(0xc2ad5066)
		year = 1999
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = punk
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -1.8
		duration = 238
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 9
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 7
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc305 = {
		checksum = dlc305
		name = 'dlc305'
		title = qs(0x301a2f7c)
		artist = qs(0x52601756)
		year = 1992
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `prog rock`
		countoff = 'sticks_huge'
		drum_kit = 'heavyrock'
		overall_song_volume = -2.0
		duration = 495
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 9
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 7
		band_difficulty_rating = 8
	}
	dlc306 = {
		checksum = dlc306
		name = 'dlc306'
		title = qs(0x6e1595b7)
		artist = qs(0xa5705512)
		year = 1968
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = 1.0
		duration = 236
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 7
		band_difficulty_rating = 6
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc307 = {
		checksum = dlc307
		name = 'dlc307'
		title = qs(0xf5d13349)
		artist = qs(0x73b91d7a)
		year = 1973
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `southern rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -1.0
		duration = 322
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc308 = {
		checksum = dlc308
		name = 'dlc308'
		title = qs(0xf39d2194)
		artist = qs(0xb09f2ddc)
		year = 1983
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `new wave`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		drum_solo = 1
		overall_song_volume = -3
		duration = 295
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
	}
	dlc309 = {
		checksum = dlc309
		name = 'dlc309'
		title = qs(0xc159841d)
		artist = qs(0xd0393a54)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `modern rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2.2
		duration = 225
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc310 = {
		checksum = dlc310
		name = 'dlc310'
		title = qs(0xe5d8f225)
		artist = qs(0xdb17f0fe)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -0.6
		duration = 256
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	dlc311 = {
		checksum = dlc311
		name = 'dlc311'
		title = qs(0x7afd3387)
		artist = qs(0xd287d747)
		year = 1996
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `surf rock`
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -4
		duration = 186
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc312 = {
		checksum = dlc312
		name = 'dlc312'
		title = qs(0x589e3470)
		artist = qs(0x15a02f7f)
		year = 1987
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = none
		genre = `hard rock`
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -3.1
		duration = 199
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 8
		band_difficulty_rating = 8
	}
	dlc313 = {
		checksum = dlc313
		name = 'dlc313'
		title = qs(0xe36a0151)
		artist = qs(0xbb1e4a7e)
		year = 2001
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `prog rock`
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -1.5
		duration = 418
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
	}
	dlc314 = {
		checksum = dlc314
		name = 'dlc314'
		title = qs(0xe5bf06d2)
		artist = qs(0xcdd4f9d7)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `nu metal`
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -2.9
		duration = 272
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 8
		band_difficulty_rating = 8
	}
	dlc315 = {
		checksum = dlc315
		name = 'dlc315'
		title = qs(0x9d884cab)
		artist = qs(0xd6fcabfc)
		year = 2000
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `pop rock`
		countoff = 'hihat01'
		drum_kit = 'heavyrock'
		overall_song_volume = -1.3
		duration = 305
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
	}
	dlc316 = {
		checksum = dlc316
		name = 'dlc316'
		title = qs(0x15039c89)
		artist = qs(0xaaa93722)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2
		duration = 368
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
		vocals_pitch_score_shift = {
			cents = 50
		}
	}
	dlc317 = {
		checksum = dlc268
		name = 'dlc317'
		title = qs(0xfe220f86)
		artist = qs(0x37d971e8)
		year = 1992
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = punk
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2.4
		duration = 169
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 180
	}
	dlc318 = {
		checksum = dlc318
		name = 'dlc318'
		title = qs(0x7a4688cb)
		artist = qs(0x83dbb173)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `pop rock`
		countoff = 'hihat01'
		drum_kit = 'modernrock'
		overall_song_volume = -2.5
		duration = 320
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 180
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 120
	}
	dlc319 = {
		checksum = dlc319
		name = 'dlc319'
		title = qs(0xd7908089)
		artist = qs(0x6e45428c)
		year = 2003
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = metal
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		performance = 1
		overall_song_volume = -3
		duration = 196
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	dlc320 = {
		checksum = dlc320
		name = 'dlc320'
		title = qs(0x6283995a)
		artist = qs(0xf25755cf)
		year = 1975
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `hard rock`
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = -1.0
		duration = 505
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc321 = {
		checksum = dlc321
		name = 'dlc321'
		title = qs(0x48297c71)
		artist = qs(0xd8375309)
		year = 1976
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `southern rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		drum_solo = 1
		overall_song_volume = -2.9
		vocals_pitch_score_shift = {
			cents = 7
		}
		duration = 386
		album_title = qs(0x3bf6da81)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc325 = {
		checksum = dlc325
		name = 'dlc325'
		title = qs(0x1120662e)
		artist = qs(0xa8051f29)
		year = 1987
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -2.4
		duration = 199
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	dlc322 = {
		checksum = dlc322
		name = 'dlc322'
		title = qs(0x01491acc)
		artist = qs(0x7d08ac42)
		year = 1973
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `classic rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = -1.5
		duration = 230
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	dlc326 = {
		checksum = dlc326
		name = 'dlc326'
		title = qs(0x41e5ad49)
		artist = qs(0x9fb8944f)
		year = 1993
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		performance = 1
		overall_song_volume = -2
		duration = 208
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 2
	}
	dlc327 = {
		checksum = dlc327
		name = 'dlc327'
		title = qs(0xd1c783e8)
		artist = qs(0x080bbcd2)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `heavy metal`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = -4.2
		duration = 232
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 1
		band_difficulty_rating = 4
	}
	dlc328 = {
		checksum = dlc328
		name = 'dlc328'
		title = qs(0xd10cb584)
		artist = qs(0xeb218361)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = pop
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = -2.3
		duration = 266
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
		vocals_pitch_score_shift = {
			cents = 35
		}
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc329 = {
		checksum = dlc329
		name = 'dlc329'
		title = qs(0xbb0bda5b)
		artist = qs(0x4b58f1d4)
		year = 1984
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = -3.8
		duration = 250
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 9
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 9
		band_difficulty_rating = 8
	}
	dlc336 = {
		checksum = dlc336
		name = 'dlc336'
		title = qs(0x3c672d6a)
		artist = qs(0x0986699d)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `indie rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = -2
		duration = 206
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 5
	}
	dlc330 = {
		checksum = dlc330
		name = 'dlc330'
		title = qs(0x2950f7b0)
		artist = qs(0x68414f08)
		year = 1970
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `southern rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -3.4
		duration = 182
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	dlc331 = {
		checksum = dlc331
		name = 'dlc331'
		title = qs(0x9629bf74)
		artist = qs(0xbb1e4a7e)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `prog rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -1.9
		duration = 429
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
	}
	dlc332 = {
		checksum = dlc332
		name = 'dlc332'
		title = qs(0x0aec3e18)
		artist = qs(0x85b9b5a3)
		year = 2002
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = pop
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2
		duration = 264
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	dlc333 = {
		checksum = dlc333
		name = 'dlc333'
		title = qs(0x7af48d06)
		artist = qs(0x462dbcd5)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `indie rock`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -1.4
		duration = 175
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 180
	}
	dlc334 = {
		checksum = dlc334
		name = 'dlc334'
		title = qs(0x877796b6)
		artist = qs(0xc49d5080)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `nu metal`
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		overall_song_volume = -2
		duration = 210
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	dlc335 = {
		checksum = dlc335
		name = 'dlc335'
		title = qs(0x4f1b69d9)
		artist = qs(0x57fef50b)
		year = 1967
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `blues rock`
		countoff = 'hihat01'
		drum_kit = 'classicrock'
		overall_song_volume = -2.9
		duration = 208
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 5
	}
}
