
script create_node_flags 
	CreateNodeFlag \{ls_mood_rising}
	CreateNodeFlag \{ls_perf_round_m5}
	CreateNodeFlag \{ls_mood_pyro}
	CreateNodeFlag \{ls_mood_exposition}
	CreateNodeFlag \{LS_MOOD_FLARE}
	CreateNodeFlag \{ls_perf_round_m2}
	CreateNodeFlag \{ls_perf_round_v}
	CreateNodeFlag \{LS_MOOD_BLACKOUT}
	CreateNodeFlag \{ls_perf_round_m7}
	CreateNodeFlag \{ls_perf_openingact}
	CreateNodeFlag \{ls_perf_round_m8}
	CreateNodeFlag \{ls_perf_round_m1}
	CreateNodeFlag \{ls_mood_silhouette}
	CreateNodeFlag \{ls_mood_climax}
	CreateNodeFlag \{ls_mood_tension}
	CreateNodeFlag \{ls_mood_prelude}
	CreateNodeFlag \{ls_perf_round_m3}
	CreateNodeFlag \{LS_MOOD_STROBE}
	CreateNodeFlag \{NODEFLAG_VIEWERLIGHTS}
	CreateNodeFlag \{ls_perf_round}
	CreateNodeFlag \{ls_perf_round_m6}
	CreateNodeFlag \{ls_mood_wash}
	CreateNodeFlag \{ls_mood_falling}
	CreateNodeFlag \{ls_mood_resolution}
	CreateNodeFlag \{ls_mood_intro}
	CreateNodeFlag \{ls_perf_round_m4}
	CreateNodeFlag \{ls_perf_standard}
endscript
