FLAG_SKATER_KILLING = 0
FLAG_SKATER_REVERTFS = 1
FLAG_SKATER_REVERTBS = 2
FLAG_SKATER_INLOOP = 3
FLAG_SKATER_LIPCOMBO = 4
FLAG_SKATER_MANUALCHEESE = 5
FLAG_SKATER_CARPLANT = 6
FLAG_SKATER_GRAB_TWEAK = 7
FLAG_SKATER_INGRAB = 8
FLAG_SKATER_INFLIP = 9
FLAG_SKATER_INMANUAL = 10
FLAG_SKATER_INLIP = 11
FLAG_SKATER_INGRIND = 12
FLAG_SKATER_INGOALINIT = 13
FLAG_SKATER_LIPTRICK_CAM_REVERSED = 14
FLAG_SKATER_REVERTCHEESE = 22

script ClearSkaterFlags 
	obj_clearflag \{$FLAG_SKATER_KILLING}
	obj_clearflag \{$FLAG_SKATER_REVERTFS}
	obj_clearflag \{$FLAG_SKATER_REVERTBS}
	obj_clearflag \{$FLAG_SKATER_INLOOP}
	obj_clearflag \{$FLAG_SKATER_LIPCOMBO}
	obj_clearflag \{$FLAG_SKATER_MANUALCHEESE}
	obj_clearflag \{$FLAG_SKATER_INGRAB}
	obj_clearflag \{$FLAG_SKATER_GRAB_TWEAK}
	obj_clearflag \{$FLAG_SKATER_INFLIP}
	obj_clearflag \{$FLAG_SKATER_INMANUAL}
	obj_clearflag \{$FLAG_SKATER_INLIP}
	obj_clearflag \{$FLAG_SKATER_INGRIND}
	obj_clearflag \{$FLAG_SKATER_REVERTCHEESE}
	obj_clearflag \{$FLAG_SKATER_INGOALINIT}
	obj_clearflag \{$FLAG_SKATER_LIPTRICK_CAM_REVERSED}
endscript
