default_sponsors = {
	deck = Birdhouse
	Clothing_Accessories = Volcom
	Shoe = Etnies
}
sponsor_product_types = {
	Decks = deck
	Clothing = Clothing_Accessories
	accessories = Clothing_Accessories
	shoes = Shoe
}
skate9_sponsors = {
	element = {
		texture = element
		lifestyle = career
		product = Clothing
		movie = 'element'
		frame = 9
		cas_type = cas_torso
		cas_desc = CAS_reg_longsleevet_element01
		cas_name = "Element Flight Flannel shirt"
		cas_flag = $CAS_UNLOCK_AM
	}
	Hurley = {
		texture = Hurley
		lifestyle = career
		product = Clothing
		movie = 'hurley'
		frame = 17
		cas_type = cas_torso
		cas_desc = cas_reg_layered_Hurley01
		cas_name = "Hurley Newsome Shirt"
		cas_flag = $CAS_UNLOCK_AM
	}
	billabong = {
		texture = billabong
		lifestyle = career
		product = Clothing
		movie = 'billabong'
		frame = 4
		cas_type = cas_torso
		cas_desc = CAS_reg_Billabong01
		cas_name = "Billabong Neptune"
		cas_flag = $CAS_UNLOCK_AM
	}
	hawk = {
		texture = hawk_clothing
		lifestyle = career
		product = Clothing
		frame = 4
		cas_type = cas_torso
		cas_desc = CAS_reg_polo_Hawk01
		cas_name = "Tony Hawk Marshall polo"
		cas_flag = $CAS_UNLOCK_AM
	}
	Nike = {
		texture = nike_sb
		lifestyle = career
		product = Clothing
		frame = 4
		cas_type = cas_torso
		cas_desc = CAS_reg_TSHIRT_Nike01
		cas_name = "Nike SB Logo Tee"
		cas_flag = $CAS_UNLOCK_AM
	}
	Oakley = {
		texture = Oakley
		lifestyle = career
		product = accessories
		movie = 'oakley'
		frame = 22
		cas_type = CAS_Glasses
		cas_desc = cas_shared_glasses_oakley01
		cas_name = "Oakley Montefrio"
		cas_flag = $CAS_UNLOCK_AM
	}
	pro_tec = {
		texture = pro_tec
		lifestyle = career
		product = accessories
		frame = 25
		cas_type = cas_hat
		cas_desc = CAS_shared_HAT_Protec02
		cas_name = "Pro-tec ace helmet"
		cas_flag = $CAS_UNLOCK_AM
	}
	Nixon = {
		texture = Nixon
		lifestyle = career
		product = accessories
		frame = 25
		cas_type = CAS_Accessory01
		cas_desc = cas_shared_watch_playerL
		cas_name = "Nixon Player"
		cas_flag = $CAS_UNLOCK_AM
	}
	Birdhouse = {
		texture = Birdhouse
		lifestyle = career
		product = Decks
		movie = 'birdhouse'
		frame = 5
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_Birdhouse_01
		cas_name = "Birdhouse Black 6"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Career_Deck
		cas_name_sig = "Signature Career Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	DGk = {
		texture = DGk
		lifestyle = career
		product = Decks
		movie = 'dgk'
		frame = 6
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_DGK_02
		cas_name = "DGK Motivation"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Career_Deck
		cas_name_sig = "Signature Career Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	plan_b = {
		texture = plan_b
		lifestyle = career
		product = Decks
		movie = 'planb'
		frame = 6
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_PlanB_07
		cas_name = "Plan B Lock Up"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Career_Deck
		cas_name_sig = "Signature Career Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	element2 = {
		texture = element
		lifestyle = career
		product = Decks
		movie = 'element'
		frame = 9
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_Element_02
		cas_name = "Element Dispersion"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Career_Deck
		cas_name_sig = "Signature Career Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	DGK2 = {
		texture = DGk
		lifestyle = career
		product = shoes
		movie = 'dgk'
		frame = 6
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeDGK
		cas_name = "DGK Club DGK Pump"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Career_Shoe
		cas_name_sig = "Signature Career Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Globe = {
		texture = Globe
		lifestyle = career
		product = shoes
		movie = 'globe'
		frame = 15
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeGlobe
		cas_name = "Globe Mace Blk/Orange"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Career_Shoe
		cas_name_sig = "Signature Career Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	element3 = {
		texture = element
		lifestyle = career
		product = shoes
		movie = 'element'
		frame = 9
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeElement
		cas_name = "Element Omahigh"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Career_Shoe
		cas_name_sig = "Signature Career Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Volcom = {
		texture = Volcom
		lifestyle = hardcore
		product = Clothing
		movie = 'volcom'
		frame = 34
		cas_type = cas_torso
		cas_desc = CAS_reg_BBTShirt_Volcom01
		cas_name = "Volcom Crossover Tank"
		cas_flag = $CAS_UNLOCK_AM
	}
	Sessions = {
		texture = Sessions
		lifestyle = hardcore
		product = Clothing
		frame = 28
		cas_type = cas_torso
		cas_desc = CAS_reg_Hoody_Split01
		cas_name = "Split Bolster Hoody"
		cas_flag = $CAS_UNLOCK_AM
	}
	zoo = {
		texture = zoo_york
		lifestyle = hardcore
		product = Clothing
		movie = 'zooyork'
		frame = 36
		cas_type = cas_torso
		cas_desc = CAS_reg_HOODY_zooyork01
		cas_name = "Zoo York Armada Zip Hoody"
		cas_flag = $CAS_UNLOCK_AM
	}
	altamont = {
		texture = altamont
		lifestyle = hardcore
		product = Clothing
		movie = 'altamont'
		frame = 36
		cas_type = cas_torso
		cas_desc = CAS_reg_JACKET_Altamont01
		cas_name = "Altamont Captain Jacket"
		cas_flag = $CAS_UNLOCK_AM
	}
	Quiksilver = {
		texture = quicksilver
		lifestyle = hardcore
		product = Clothing
		movie = 'quiksilver'
		frame = 26
		cas_type = cas_torso
		cas_desc = CAS_reg_SWEATER_Quik01
		cas_name = "Quiksilver Stranglehold Sweater"
		cas_flag = $CAS_UNLOCK_AM
	}
	Electric = {
		texture = Electric
		lifestyle = hardcore
		product = accessories
		movie = 'Electric'
		frame = 8
		cas_type = CAS_Glasses
		cas_desc = cas_shared_generator
		cas_name = "Electric Generator"
		cas_flag = $CAS_UNLOCK_AM
	}
	ogio = {
		texture = ogio
		lifestyle = hardcore
		product = accessories
		movie = 'ogio'
		frame = 23
		cas_type = cas_torso
		cas_desc = CAS_reg_Pack_ogio04
		cas_name = "Ogio Legend backpack"
		cas_flag = $CAS_UNLOCK_AM
	}
	Nixon2 = {
		texture = Nixon
		lifestyle = hardcore
		product = accessories
		frame = 25
		cas_type = CAS_Accessory01
		cas_desc = cas_shared_watch_rockerL
		cas_name = "Nixon Rocker"
		cas_flag = $CAS_UNLOCK_AM
	}
	flippy = {
		texture = flip
		lifestyle = hardcore
		product = Decks
		movie = 'flipper'
		frame = 13
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_Flip_03
		cas_name = "Flip Team Alchemy"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Hardcore_Deck
		cas_name_sig = "Signature Hardcore Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	Baker = {
		texture = Baker
		lifestyle = hardcore
		product = Decks
		movie = 'baker'
		frame = 3
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_Baker_06
		cas_name = "Baker Hardly a Logo"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Hardcore_Deck
		cas_name_sig = "Signature Hardcore Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	zoo2 = {
		texture = zoo_york
		lifestyle = hardcore
		product = Decks
		movie = 'zooyork'
		frame = 36
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_ZooYork_02
		cas_name = "Zoo York Predator"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Hardcore_Deck
		cas_name_sig = "Signature Hardcore Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	emerica = {
		texture = emerica
		lifestyle = hardcore
		product = shoes
		aspect = 1.0
		movie = 'emerica'
		frame = 12
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeEmerica
		cas_name = "Emerica McNally Bishop"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Hardcore_Shoe
		cas_name_sig = "Signature Hardcore Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Etnies = {
		texture = Etnies
		lifestyle = hardcore
		product = shoes
		aspect = 1.0
		movie = 'etnies'
		frame = 12
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeEtnies
		cas_name = "Etnies annex red/black"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Hardcore_Shoe
		cas_name_sig = "Signature Hardcore Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Adio = {
		texture = Adio
		lifestyle = hardcore
		product = shoes
		movie = 'adio'
		frame = 0
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeAdio
		cas_name = "Adio Kenny Standard"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Hardcore_Shoe
		cas_name_sig = "Signature Hardcore Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Matix = {
		texture = Matix
		lifestyle = rigger
		product = Clothing
		movie = 'matix'
		frame = 19
		cas_type = cas_torso
		cas_desc = CAS_reg_SWEATER_Matix01
		cas_name = "Matix Intel Sweater"
		cas_flag = $CAS_UNLOCK_AM
	}
	independent = {
		texture = independent
		lifestyle = rigger
		product = Clothing
		frame = 18
		cas_type = cas_torso
		cas_desc = CAS_reg_HOODY_Indy01
		cas_name = "Indy Primitive Hoody"
		cas_flag = $CAS_UNLOCK_AM
	}
	split = {
		texture = split
		lifestyle = rigger
		product = Clothing
		frame = 31
		cas_type = cas_torso
		cas_desc = CAS_reg_Hoody_Split01
		cas_name = "Split Bolster Hoody"
		cas_flag = $CAS_UNLOCK_AM
	}
	RDS = {
		texture = RDS
		lifestyle = rigger
		product = Clothing
		frame = 33
		cas_type = cas_torso
		cas_desc = CAS_reg_HOODY_RDS01
		cas_name = "RDS Delancy Hoody"
		cas_flag = $CAS_UNLOCK_AM
	}
	Vans = {
		texture = Vans
		lifestyle = rigger
		product = Clothing
		movie = 'vans'
		frame = 33
		cas_type = cas_torso
		cas_desc = CAS_reg_HOODY_vans02
		cas_name = "Vans AV Flannel Hood"
		cas_flag = $CAS_UNLOCK_AM
	}
	VonZipper = {
		texture = von_zipper
		lifestyle = rigger
		product = accessories
		movie = 'vonzipper'
		frame = 35
		cas_type = CAS_Glasses
		cas_desc = cas_shared_glasses_vonzip05
		cas_name = "VonZipper Gamma"
		cas_flag = $CAS_UNLOCK_AM
	}
	skull_candy = {
		texture = skull_candy
		lifestyle = rigger
		product = accessories
		frame = 29
		cas_type = CAS_Accessory03
		cas_desc = CAS_ACC_skullcandy02
		cas_name = "Skullcandy Lowrider"
		cas_flag = $CAS_UNLOCK_AM
	}
	nixon3 = {
		texture = Nixon
		lifestyle = rigger
		product = accessories
		frame = 25
		cas_type = CAS_Accessory01
		cas_desc = cas_shared_watch_rotologL
		cas_name = "Nixon Rotolog"
		cas_flag = $CAS_UNLOCK_AM
	}
	Almost = {
		texture = Almost
		lifestyle = rigger
		product = Decks
		movie = 'almost'
		frame = 1
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_Almost_02
		cas_name = "Almost Coffin Cruiser"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Rigger_Deck
		cas_name_sig = "Signature Rigger Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	RDS2 = {
		texture = RDS
		lifestyle = rigger
		product = Decks
		frame = 33
		cas_type = CAS_DECK_GRAPHIC
		cas_desc = Decks_RDS_02
		cas_name = "RDS 2"
		cas_flag = $CAS_UNLOCK_DECK
		cas_type_sig = CAS_DECK_GRAPHIC
		cas_desc_sig = Signature_Rigger_Deck
		cas_name_sig = "Signature Rigger Deck"
		cas_flag_sig = $CAS_UNLOCK_DECK_SIG
	}
	DVS = {
		texture = DVS
		lifestyle = rigger
		product = shoes
		movie = 'DVS'
		frame = 7
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeDVS
		cas_name = "DVS Regency"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Rigger_Shoe
		cas_name_sig = "Signature Rigger Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	eS = {
		texture = eS
		lifestyle = rigger
		product = shoes
		movie = 'eS'
		frame = 11
		cas_type = cas_shoes
		cas_desc = CAS_shared_GshoeEs
		cas_name = "éS Arklow Maroon/Wht"
		text_case = none
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Rigger_Shoe
		cas_name_sig = "Signature Rigger Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
	Vans2 = {
		texture = Vans
		lifestyle = rigger
		product = shoes
		movie = 'vans'
		frame = 33
		cas_type = cas_shoes
		cas_desc = CAS_shared_shoeVans06
		cas_name = "Vans DD-66"
		cas_flag = $CAS_UNLOCK_SHOE
		cas_type_sig = cas_shoes
		cas_desc_sig = CAS_signature_Rigger_Shoe
		cas_name_sig = "Signature Rigger Shoe"
		cas_flag_sig = $CAS_UNLOCK_SHOE_SIG
	}
}
