gh4_dlc_songlist = [
	DLC1
	DLC2
	DLC3
	DLC4
	DLC5
	DLC6
	DLC7
	DLC8
	DLC9
	DLC10
	DLC46
	dlc11
	dlc12
	dlc13
	dlc14
	dlc15
	dlc16
	dlc17
	dlc18
	dlc19
	dlc20
	dlc21
	DLC25
	DLC26
	DLC27
	DLC28
	DLC29
	DLC30
	DLC31
	DLC32
	DLC33
	DLC34
	DLC35
	DLC36
	DLC37
	DLC38
	DLC39
	DLC40
	DLC41
	DLC42
	DLC43
	DLC44
	DLC45
	DLC51
	DLC52
	DLC53
	DLC54
	DLC55
	DLC56
	DLC57
	DLC47
	DLC48
	DLC49
	DLC58
	DLC59
	DLC60
	DLC61
	DLC62
	DLC63
	DLC64
	DLC65
	DLC66
	DLC67
	DLC68
	DLC69
	DLC70
	DLC71
	DLC72
	DLC73
	DLC74
	DLC75
	DLC76
	DLC77
	DLC78
	DLC79
	DLC80
	DLC81
	DLC82
	DLC83
	DLC84
	DLC85
	DLC88
	DLC89
	DLC90
	DLC86
	DLC87
	DLC91
	DLC93
	DLC94
	DLC95
	DLC99
	DLC101
	DLC102
	DLC103
	DLC104
	DLC105
	DLC107
	DLC108
	DLC109
	DLC113
	DLC114
	DLC115
	DLC110
	DLC111
	DLC112
	DLC98
	DLC100
	DLC106
	DLC50
	DLC122
	DLC116
	DLC117
	DLC118
	DLC119
	DLC120
	DLC121
	DLC123
	DLC124
	DLC125
	DLC126
	DLC127
	DLC128
	DLC129
	DLC130
	DLC131
	DLC132
	DLC136
	DLC137
	DLC138
	DLC139
	DLC140
	DLC141
	DLC142
	DLC143
	DLC144
	DLC151
	DLC152
	DLC153
	DLC154
	DLC148
	DLC149
	DLC150
	DLC134
	DLC133
	DLC135
	DLC155
	DLC156
	DLC157
	DLC161
	DLC162
	DLC163
	DLC164
]
gh4_dlc_songlist_props = {
	DLC1 = {
		checksum = DLC1
		name = 'dlc1'
		Title = qs(0x259ac475)
		artist = qs(0xf25755cf)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = rock
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 3.8
		Duration = 201
		album_title = qs(0x5b7eab5e)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
	}
	DLC2 = {
		checksum = DLC2
		name = 'dlc2'
		Title = qs(0xddfccda2)
		artist = qs(0x98fdbfd6)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 1.2
		Duration = 221
		album_title = qs(0x5b7eab5e)
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 2
		band_difficulty_rating = 5
	}
	DLC3 = {
		checksum = DLC3
		name = 'dlc3'
		Title = qs(0x0cf7e049)
		artist = qs(0xaa6cfe89)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = `Prog	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 289
		double_kick = 1
		album_title = qs(0x74fcbd50)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 9
		band_difficulty_rating = 6
	}
	DLC4 = {
		checksum = DLC4
		name = 'dlc4'
		Title = qs(0x8d4935c8)
		artist = qs(0x218f108a)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = electronic
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'hiphop'
		vocals_scroll_speed = 1.5
		Duration = 213
		album_title = qs(0x218f108a)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	DLC5 = {
		checksum = DLC5
		name = 'dlc5'
		Title = qs(0x559878cb)
		artist = qs(0xc190c790)
		year = 1976
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 184
		album_title = qs(0xc190c790)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 9
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	DLC6 = {
		checksum = DLC6
		name = 'dlc6'
		Title = qs(0x133c3889)
		artist = qs(0x5b3ab1bb)
		year = 1978
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 201
		album_title = qs(0xb6f596cb)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
	}
	DLC7 = {
		checksum = DLC7
		name = 'dlc7'
		Title = qs(0xd2aca776)
		artist = qs(0x8fee44fb)
		year = 1981
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 199
		album_title = qs(0xc8bbe5e9)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	DLC8 = {
		checksum = DLC8
		name = 'dlc8'
		Title = qs(0x1866c045)
		artist = qs(0xaa45dcf6)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Surf	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 215
		album_title = qs(0xdf915130)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
	}
	DLC9 = {
		checksum = DLC9
		name = 'dlc9'
		Title = qs(0x6f2dc4ce)
		artist = qs(0x5bd485d8)
		year = 1992
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 223
		album_title = qs(0x5bd485d8)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC10 = {
		checksum = DLC10
		name = 'dlc10'
		Title = qs(0xd308b6b4)
		artist = qs(0xdf0eba71)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Surf	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 231
		album_title = qs(0x219e65d0)
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
	}
	dlc11 = {
		checksum = dlc11
		name = 'dlc11'
		Title = qs(0x677994a6)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 304
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
	}
	dlc12 = {
		checksum = dlc12
		name = 'dlc12'
		Title = qs(0x5ee0b5ba)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 483
		double_kick = 1
		vocals_scroll_speed = 1.2700001
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 7
	}
	dlc13 = {
		checksum = dlc13
		name = 'dlc13'
		Title = qs(0xf8de7350)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 435
		double_kick = 1
		vocals_scroll_speed = 1.63
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
	}
	dlc14 = {
		checksum = dlc14
		name = 'dlc14'
		Title = qs(0xbd0cac2c)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 477
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 7
	}
	dlc15 = {
		checksum = dlc15
		name = 'dlc15'
		Title = qs(0x60bb303f)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 397
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 7
		band_difficulty_rating = 7
	}
	dlc16 = {
		checksum = dlc16
		name = 'dlc16'
		Title = qs(0x92c46fd5)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 489
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 7
		band_difficulty_rating = 7
	}
	dlc17 = {
		checksum = dlc17
		name = 'dlc17'
		Title = qs(0x028d047e)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 487
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc18 = {
		checksum = dlc18
		name = 'dlc18'
		Title = qs(0xa66e82f5)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 480
		double_kick = 0
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	dlc19 = {
		checksum = dlc19
		name = 'dlc19'
		Title = qs(0x6525555e)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 404
		double_kick = 1
		vocals_scroll_speed = 1.15
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 5
		band_difficulty_rating = 6
	}
	dlc20 = {
		checksum = dlc20
		name = 'dlc20'
		Title = qs(0xf381c77a)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 597
		double_kick = 1
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	dlc21 = {
		checksum = dlc21
		name = 'dlc21'
		Title = qs(0x3f2bc7e4)
		artist = qs(0x4b58f1d4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 597
		double_kick = 1
		album_title = qs(0x8438fc89)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC25 = {
		checksum = DLC25
		name = 'dlc25'
		Title = qs(0x86416821)
		artist = qs(0xa8051f29)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = 0
		Duration = 149
		album_title = qs(0x1f97dea4)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC26 = {
		checksum = DLC26
		name = 'dlc26'
		Title = qs(0x9d37cac0)
		artist = qs(0xa8051f29)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = 0
		Duration = 162
		album_title = qs(0x1f97dea4)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC27 = {
		checksum = DLC27
		name = 'dlc27'
		Title = qs(0x1e64fbf7)
		artist = qs(0xa8051f29)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'fusion'
		overall_song_volume = 0
		Duration = 211
		album_title = qs(0x1f97dea4)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 5
		band_difficulty_rating = 3
	}
	DLC28 = {
		checksum = DLC28
		name = 'dlc28'
		Title = qs(0x70e7c6d0)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 295
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC29 = {
		checksum = DLC29
		name = 'dlc29'
		Title = qs(0x52dc4c94)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 308
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
	}
	DLC30 = {
		checksum = DLC30
		name = 'dlc30'
		Title = qs(0xd75ed831)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 191
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC31 = {
		checksum = DLC31
		name = 'dlc31'
		Title = qs(0xfa7393a3)
		artist = qs(0xfeac2b68)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 207
		album_title = qs(0x85b3b642)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC32 = {
		checksum = DLC32
		name = 'dlc32'
		Title = qs(0xb0e242dd)
		artist = qs(0xfeac2b68)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 217
		album_title = qs(0x85b3b642)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC33 = {
		checksum = DLC33
		name = 'dlc33'
		Title = qs(0x017d220b)
		artist = qs(0xfeac2b68)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.2
		Duration = 188
		album_title = qs(0x85b3b642)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 9
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
	}
	DLC34 = {
		checksum = DLC34
		name = 'dlc34'
		Title = qs(0x4b01dd2c)
		artist = qs(0x2fc08707)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		Duration = 248
		album_title = qs(0x8c0dbbb9)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = -2
	}
	DLC35 = {
		checksum = DLC35
		name = 'dlc35'
		Title = qs(0xb3803492)
		artist = qs(0x2fc08707)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		Duration = 247
		album_title = qs(0x8c0dbbb9)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = -2
	}
	DLC36 = {
		checksum = DLC36
		name = 'dlc36'
		Title = qs(0x0409d1b8)
		artist = qs(0x2fc08707)
		year = 2003
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'modernrock'
		Duration = 228
		album_title = qs(0x76e6c2ae)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = -2
	}
	DLC37 = {
		checksum = DLC37
		name = 'dlc37'
		Title = qs(0x71153b35)
		artist = qs(0x9fb8944f)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 203
		album_title = qs(0x6914dc26)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 5
		band_difficulty_rating = 3
	}
	DLC38 = {
		checksum = DLC38
		name = 'dlc38'
		Title = qs(0x30b78117)
		artist = qs(0x9fb8944f)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		double_kick = 0
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 270
		album_title = qs(0x24efe732)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 1
		band_difficulty_rating = 2
	}
	DLC39 = {
		checksum = DLC39
		name = 'dlc39'
		Title = qs(0x03d6a77a)
		artist = qs(0x9fb8944f)
		year = 1999
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 248
		album_title = qs(0x5d595a23)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 4
	}
	DLC40 = {
		checksum = DLC40
		name = 'dlc40'
		Title = qs(0xd8b125a7)
		artist = qs(0x5a827f81)
		year = 2002
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 217
		album_title = qs(0x5a827f81)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC41 = {
		checksum = DLC41
		name = 'dlc41'
		Title = qs(0x703bdfb5)
		artist = qs(0x5a827f81)
		year = 1989
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		double_kick = 1
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 182
		album_title = qs(0xdfe4cf29)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	DLC42 = {
		checksum = DLC42
		name = 'dlc42'
		Title = qs(0x9463ecd1)
		artist = qs(0x5a827f81)
		year = 1990
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 135
		album_title = qs(0x819c04ad)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 3
	}
	DLC51 = {
		checksum = DLC51
		name = 'dlc51'
		Title = qs(0xb0a0385a)
		artist = qs(0xb902bb25)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.2
		Duration = 271
		album_title = qs(0xf664f602)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC43 = {
		checksum = DLC43
		name = 'dlc43'
		Title = qs(0x145ca491)
		artist = qs(0x4f0cce27)
		year = 1976
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 290
		album_title = qs(0x12217b98)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
	}
	DLC44 = {
		checksum = DLC44
		name = 'dlc44'
		Title = qs(0xbfe00f44)
		artist = qs(0x4f0cce27)
		year = 1975
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 279
		album_title = qs(0xbfe00f44)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	DLC45 = {
		checksum = DLC45
		name = 'dlc45'
		Title = qs(0x3d8d8877)
		artist = qs(0x4f0cce27)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 354
		album_title = qs(0xbc128aee)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	DLC46 = {
		checksum = DLC46
		name = 'dlc46'
		Title = qs(0xc39b48ea)
		artist = qs(0xde6bdbec)
		year = 2004
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Surf	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 2
		vocals_scroll_speed = 1.5
		Duration = 286
		album_title = qs(0xde6bdbec)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	DLC52 = {
		checksum = DLC52
		name = 'dlc52'
		Title = qs(0xb1e511f2)
		artist = qs(0xc9b243c0)
		year = 1999
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 218
		album_title = qs(0xf9241aff)
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
	}
	DLC53 = {
		checksum = DLC53
		name = 'dlc53'
		Title = qs(0x40d459e3)
		artist = qs(0x98a9be19)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 169
		album_title = qs(0x2d0713f0)
		guitar_difficulty_rating = 1
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 1
		band_difficulty_rating = 2
	}
	DLC54 = {
		checksum = DLC54
		name = 'dlc54'
		Title = qs(0xf4df9c34)
		artist = qs(0x46ea452b)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		parts_with_mic = [
			Guitarist
		]
		overall_song_volume = 0
		Duration = 271
		album_title = qs(0xf4df9c34)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC55 = {
		checksum = DLC55
		name = 'dlc55'
		Title = qs(0xf93f5e1d)
		artist = qs(0xe3d868ac)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 163
		album_title = qs(0xe3d868ac)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	DLC56 = {
		checksum = DLC56
		name = 'dlc56'
		Title = qs(0x8ffd4eb4)
		artist = qs(0xe2619622)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.2
		Duration = 218
		album_title = qs(0xe2619622)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
	}
	DLC57 = {
		checksum = DLC57
		name = 'dlc57'
		Title = qs(0x6f300994)
		artist = qs(0x1ce01fd6)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 146
		album_title = qs(0x98a9469e)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC47 = {
		checksum = DLC47
		name = 'dlc47'
		Title = qs(0x1d551284)
		artist = qs(0x6f536e53)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 261
		album_title = qs(0x52081154)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC48 = {
		checksum = DLC48
		name = 'dlc48'
		Title = qs(0xc432f0f6)
		artist = qs(0xf45c5c52)
		year = 2003
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		double_kick = 1
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 221
		album_title = qs(0x4c3f8e1f)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC49 = {
		checksum = DLC49
		name = 'dlc49'
		Title = qs(0x40866eb6)
		artist = qs(0x4b1bc4ee)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 243
		album_title = qs(0x492b00bd)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	DLC58 = {
		checksum = DLC58
		name = 'dlc58'
		Title = qs(0xd30f477b)
		artist = qs(0x6b9c6336)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Country
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 220
		album_title = qs(0xd30f477b)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 4
		band_difficulty_rating = 5
	}
	DLC59 = {
		checksum = DLC59
		name = 'dlc59'
		Title = qs(0x0fdd9c98)
		artist = qs(0x24fc2dc8)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Country
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 305
		album_title = qs(0xac253842)
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 3
		band_difficulty_rating = 6
	}
	DLC60 = {
		checksum = DLC60
		name = 'dlc60'
		Title = qs(0xb02a79bb)
		artist = qs(0x15065f8c)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Country
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 272
		album_title = qs(0xb02a79bb)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	DLC61 = {
		checksum = DLC61
		name = 'dlc61'
		Title = qs(0x1c2cc3eb)
		artist = qs(0xa92c5d80)
		year = 1999
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Punk`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 147
		album_title = qs(0x648f95ef)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = 0
	}
	DLC62 = {
		checksum = DLC62
		name = 'dlc62'
		Title = qs(0x981f8735)
		artist = qs(0x68674f19)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Punk`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.3
		Duration = 240
		album_title = qs(0x044398f1)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	DLC63 = {
		checksum = DLC63
		name = 'dlc63'
		Title = qs(0x8d876f81)
		artist = qs(0x6e50bae8)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = hip_hop
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.4
		Duration = 263
		album_title = qs(0xd89d5754)
		guitar_difficulty_rating = 1
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
	}
	DLC64 = {
		checksum = DLC64
		name = 'dlc64'
		Title = qs(0xb3bb926f)
		artist = qs(0x15c1e33a)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 264
		album_title = qs(0x15c1e33a)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 3
		band_difficulty_rating = 2
	}
	DLC65 = {
		checksum = DLC65
		name = 'dlc65'
		Title = qs(0xabc2e4a4)
		artist = qs(0x4713a978)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 271
		album_title = qs(0x7742a1f5)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
		vocals_pitch_score_shift = {
			cents = -22
		}
	}
	DLC66 = {
		checksum = DLC66
		name = 'dlc66'
		Title = qs(0x143d3bfe)
		artist = qs(0xb362d2df)
		year = 2002
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 184
		album_title = qs(0xe5b94845)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 3
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
		overall_song_volume = 0
	}
	DLC67 = {
		checksum = DLC67
		name = 'dlc67'
		Title = qs(0x2e15e6cf)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 295
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 3
		band_difficulty_rating = 2
	}
	DLC68 = {
		checksum = DLC68
		name = 'dlc68'
		Title = qs(0xde312b9c)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 249
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 1
		band_difficulty_rating = 2
	}
	DLC69 = {
		checksum = DLC69
		name = 'dlc69'
		Title = qs(0x2307d6b2)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 272
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	DLC70 = {
		checksum = DLC70
		name = 'dlc70'
		Title = qs(0x94a0afe5)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 269
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC71 = {
		checksum = DLC71
		name = 'dlc71'
		Title = qs(0x2b456bce)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 290
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 1
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 1
		band_difficulty_rating = 2
	}
	DLC72 = {
		checksum = DLC72
		name = 'dlc72'
		Title = qs(0x75913398)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 140
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 3
		band_difficulty_rating = 2
	}
	DLC73 = {
		checksum = DLC73
		name = 'dlc73'
		Title = qs(0xec8eb3e3)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 2.0
		Duration = 232
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC74 = {
		checksum = DLC74
		name = 'dlc74'
		Title = qs(0xa2faf4f9)
		artist = qs(0xaaa93722)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 295
		album_title = qs(0xf3ab61a0)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC75 = {
		checksum = DLC75
		name = 'dlc75'
		Title = qs(0x8f4e5208)
		artist = qs(0xcc982eb5)
		covered_by = $cover_artist_text
		covered_by_text = $cover_artist_text_by
		year = 1977
		artist_text = $artist_text_as_made_famous_by
		original_artist = 0
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 243
		album_title = $cover_artist_text
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 7
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 156
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 99
	}
	DLC76 = {
		checksum = DLC76
		name = 'dlc76'
		Title = qs(0xe20fe536)
		artist = qs(0x68414f08)
		year = 1969
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Southern	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 164
		album_title = qs(0xd7fb4998)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 165
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 120
	}
	DLC77 = {
		checksum = DLC77
		name = 'dlc77'
		Title = qs(0x9be5fca2)
		artist = qs(0x4d1adb22)
		covered_by = $cover_artist_text
		covered_by_text = $cover_artist_text_by
		year = 1983
		artist_text = $artist_text_as_made_famous_by
		original_artist = 0
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 257
		album_title = $cover_artist_text
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC78 = {
		checksum = DLC78
		name = 'dlc78'
		Title = qs(0x4a40d990)
		artist = qs(0x12371fe9)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 243
		album_title = qs(0x4a40d990)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 3
		band_difficulty_rating = 2
	}
	DLC79 = {
		checksum = DLC79
		name = 'dlc79'
		Title = qs(0x7351eb47)
		artist = qs(0x12371fe9)
		year = 1975
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -2.5
		Duration = 273
		album_title = qs(0x7351eb47)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 7
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC80 = {
		checksum = DLC80
		name = 'dlc80'
		Title = qs(0x6d69810d)
		artist = qs(0x12a28bfd)
		year = 1974
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 264
		album_title = qs(0x6d69810d)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC81 = {
		checksum = DLC81
		name = 'dlc81'
		Title = qs(0x03cbcea2)
		artist = qs(0x12a28bfd)
		year = 1972
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 191
		album_title = qs(0x987bc02a)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC82 = {
		checksum = DLC82
		name = 'dlc82'
		Title = qs(0x2807b424)
		artist = qs(0x12a28bfd)
		year = 1973
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 250
		album_title = qs(0x3d49899b)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC83 = {
		checksum = DLC83
		name = 'dlc83'
		Title = qs(0xa79a582c)
		artist = qs(0x5cc473e7)
		year = 2004
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 254
		album_title = qs(0x0c5c48a8)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 0
		band_difficulty_rating = 3
	}
	DLC84 = {
		checksum = DLC84
		name = 'dlc84'
		Title = qs(0xa7e2d671)
		artist = qs(0x53e5aebc)
		year = 2001
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 235
		album_title = qs(0x3da01c7f)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC85 = {
		checksum = DLC85
		name = 'dlc85'
		Title = qs(0x16d229fe)
		artist = qs(0x744c0318)
		year = 1999
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Surf	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 240
		album_title = qs(0x1fdca990)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
	}
	DLC88 = {
		checksum = DLC88
		name = 'dlc88'
		Title = qs(0x636ac445)
		artist = qs(0x49e5c50c)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 216
		album_title = qs(0x6cb6470f)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 3
	}
	DLC89 = {
		checksum = dlc898
		name = 'dlc89'
		Title = qs(0xfe098a9a)
		artist = qs(0x543871bf)
		year = 2003
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 241
		album_title = qs(0xfe098a9a)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 2
		band_difficulty_rating = 2
	}
	DLC90 = {
		checksum = DLC90
		name = 'dlc90'
		Title = qs(0x8c0aa35b)
		artist = qs(0x025d83fd)
		year = 1986
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 353
		album_title = qs(0xc9fd3aca)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
	}
	DLC86 = {
		checksum = DLC86
		name = 'dlc86'
		Title = qs(0x7224e87f)
		artist = qs(0x9618326b)
		year = 1978
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 219
		album_title = qs(0xc4a8d813)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	DLC87 = {
		checksum = DLC87
		name = 'dlc87'
		Title = qs(0xe1d6cf3e)
		artist = qs(0x9618326b)
		year = 1980
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 242
		album_title = qs(0xdd5a8138)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC91 = {
		checksum = DLC91
		name = 'dlc91'
		Title = qs(0x5b3ccc92)
		artist = qs(0x841bde75)
		year = 1974
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		vocals_scroll_speed = 1.3
		Duration = 164
		album_title = qs(0xf6061aa9)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC99 = {
		checksum = DLC99
		name = 'dlc99'
		Title = qs(0x67a06fd5)
		artist = qs(0xce60b2de)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		Guitarist = male
		genre = `Nu	Metal`
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 0
		Duration = 315
		album_title = qs(0x606235a5)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
	}
	DLC101 = {
		checksum = DLC101
		name = 'dlc101'
		Title = qs(0x5a969062)
		artist = qs(0xa3dc2bc4)
		year = 2001
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 263
		album_title = qs(0xd8de6f93)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC102 = {
		checksum = DLC102
		name = 'dlc102'
		Title = qs(0x84434e8d)
		artist = qs(0x0d0383d4)
		year = 1988
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 240
		album_title = qs(0x4e869070)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
	}
	DLC103 = {
		checksum = DLC103
		name = 'dlc103'
		Title = qs(0xacbc0fc0)
		artist = qs(0xb804b6c4)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = -1
		Duration = 221
		album_title = qs(0x806a6361)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 5
	}
	DLC104 = {
		checksum = DLC104
		name = 'dlc104'
		Title = qs(0x63440848)
		artist = qs(0x0b0a8b8a)
		year = 1978
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 2
		Duration = 260
		album_title = qs(0x937a1a6d)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
	}
	DLC105 = {
		checksum = DLC105
		name = 'dlc105'
		Title = qs(0x3dd6f1f3)
		artist = qs(0x0b0a8b8a)
		year = 1977
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 1
		Duration = 183
		album_title = qs(0x3c5e2823)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 1
		band_difficulty_rating = 3
	}
	DLC107 = {
		checksum = DLC107
		name = 'dlc107'
		Title = qs(0xb972b46c)
		artist = qs(0xba3d637f)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 210
		album_title = qs(0x59773dda)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC108 = {
		checksum = DLC108
		name = 'dlc108'
		Title = qs(0x8bac50f2)
		artist = qs(0xba3d637f)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 190
		album_title = qs(0x8bac50f2)
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC109 = {
		checksum = DLC109
		name = 'dlc109'
		Title = qs(0x23ec6752)
		artist = qs(0xba3d637f)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 214
		album_title = qs(0x59773dda)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
	}
	DLC110 = {
		checksum = DLC110
		name = 'dlc110'
		Title = qs(0x0824c07d)
		artist = qs(0x504043ab)
		year = 1973
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 323
		album_title = qs(0xc92200f8)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 6
		band_difficulty_rating = 6
	}
	DLC111 = {
		checksum = DLC111
		name = 'dlc111'
		Title = qs(0x04f00fde)
		artist = qs(0x504043ab)
		year = 1975
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 226
		album_title = qs(0xbeedb435)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
	}
	DLC112 = {
		checksum = DLC112
		name = 'dlc112'
		Title = qs(0xc2457b50)
		artist = qs(0x504043ab)
		year = 1976
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Classic	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 286
		album_title = qs(0x628a2cac)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
	}
	DLC93 = {
		checksum = DLC93
		name = 'dlc93'
		Title = qs(0x7f11d8bc)
		artist = qs(0xd0393a54)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 0
		Duration = 155
		album_title = qs(0x5b7eab5e)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	DLC94 = {
		checksum = DLC94
		name = 'dlc94'
		Title = qs(0xde55bc8d)
		artist = qs(0xd0393a54)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 0
		Duration = 233
		album_title = qs(0x23bd53cf)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 7
		band_difficulty_rating = 4
	}
	DLC95 = {
		checksum = DLC95
		name = 'dlc95'
		Title = qs(0xe804de45)
		artist = qs(0xd0393a54)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		overall_song_volume = 0
		Duration = 244
		album_title = qs(0xd015195f)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC98 = {
		checksum = DLC98
		name = 'dlc98'
		Title = qs(0xec28d13c)
		artist = qs(0x5e5e45df)
		year = 1991
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 183
		album_title = qs(0xaea8aa0b)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC100 = {
		checksum = DLC100
		name = 'dlc100'
		Title = qs(0x5c27721d)
		artist = qs(0x5e5e45df)
		year = 1989
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 198
		album_title = qs(0x3afd70b7)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 1
		band_difficulty_rating = 2
	}
	DLC106 = {
		checksum = DLC106
		name = 'dlc106'
		Title = qs(0x249f3442)
		artist = qs(0x5e5e45df)
		year = 1989
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 185
		album_title = qs(0x3afd70b7)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
	}
	DLC113 = {
		checksum = DLC113
		name = 'dlc113'
		Title = qs(0xc9827e11)
		artist = qs(0x3e6463ce)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 255
		album_title = qs(0x07dfa895)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 6
		band_difficulty_rating = 4
	}
	DLC114 = {
		checksum = DLC114
		name = 'dlc114'
		Title = qs(0xdf8efb66)
		artist = qs(0x3e6463ce)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 287
		album_title = qs(0x83fc9fc8)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
	}
	DLC115 = {
		checksum = DLC115
		name = 'dlc115'
		Title = qs(0xc5f7ff65)
		artist = qs(0x3e6463ce)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 345
		album_title = qs(0x83fc9fc8)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
	}
	DLC50 = {
		checksum = DLC50
		name = 'dlc50'
		Title = qs(0x0d080463)
		artist = qs(0x45d95cfd)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = `Hard	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 254
		album_title = qs(0xf664f602)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
	}
	DLC122 = {
		checksum = DLC122
		name = 'dlc122'
		Title = qs(0xb354decc)
		artist = qs(0xf738a3b3)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = rock
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 233
		album_title = qs(0x5b5d91fb)
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 4
		band_difficulty_rating = 6
	}
	DLC116 = {
		checksum = DLC116
		name = 'DLC116'
		Title = qs(0xe8279305)
		artist = qs(0x579cabf0)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 376
		album_title = qs(0xb84a18dd)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 4
		band_difficulty_rating = 7
		overall_song_volume = 0
		vocals_scroll_speed = 1.3
	}
	DLC117 = {
		checksum = DLC117
		name = 'DLC117'
		Title = qs(0x139ad44b)
		artist = qs(0x579cabf0)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 349
		album_title = qs(0xb84a18dd)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 3
		band_difficulty_rating = 7
		overall_song_volume = 0
		vocals_scroll_speed = 1.2
	}
	DLC118 = {
		checksum = DLC118
		name = 'DLC118'
		Title = qs(0x77337173)
		artist = qs(0x579cabf0)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 300
		album_title = qs(0xb84a18dd)
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC119 = {
		checksum = DLC119
		name = 'DLC119'
		Title = qs(0xb2084b9e)
		artist = qs(0x152e0356)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Death	Metal`
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 216
		album_title = qs(0x0a03cb11)
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
		overall_song_volume = 0
	}
	DLC120 = {
		checksum = DLC120
		name = 'DLC120'
		Title = qs(0xbd689ff5)
		artist = qs(0x65c3388f)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Funk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 232
		album_title = qs(0x02039113)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC121 = {
		checksum = DLC121
		name = 'DLC121'
		Title = qs(0x3bd8954a)
		artist = qs(0x047d06b2)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Indie	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 212
		album_title = qs(0xbdb4cd94)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC123 = {
		checksum = DLC123
		name = 'DLC123'
		Title = qs(0xe4897fa6)
		artist = qs(0xf7ec9dc8)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 227
		album_title = qs(0x5f325516)
		overall_song_volume = 0
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 9
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
	}
	DLC124 = {
		checksum = DLC124
		name = 'DLC124'
		Title = qs(0x742b0639)
		artist = qs(0x08e42919)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 246
		overall_song_volume = 0
		album_title = qs(0xb48ac3f5)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 2
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 154
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC125 = {
		checksum = DLC125
		name = 'DLC125'
		Title = qs(0x61394b03)
		artist = qs(0xdfb84fab)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Metal
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'heavyrock'
		Duration = 251
		overall_song_volume = 0
		album_title = qs(0x4780e5d3)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC126 = {
		checksum = DLC126
		name = 'DLC126'
		Title = qs(0x4f0a2edc)
		artist = qs(0x5a827f81)
		year = 1993
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 119
		album_title = qs(0xf069f145)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC127 = {
		checksum = DLC127
		name = 'DLC127'
		Title = qs(0xc651d475)
		artist = qs(0x5a827f81)
		year = 1993
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 210
		album_title = qs(0xe5ded0e5)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC128 = {
		checksum = DLC128
		name = 'DLC128'
		Title = qs(0x2ba77ad9)
		artist = qs(0x5a827f81)
		year = 1991
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Grunge
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 215
		album_title = qs(0x39664e39)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 7
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC129 = {
		checksum = DLC129
		name = 'DLC129'
		Title = qs(0xa691bb9a)
		artist = qs(0x8e072fe9)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 233
		album_title = qs(0x0f03dcb0)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC130 = {
		checksum = DLC130
		name = 'DLC130'
		Title = qs(0xa4130561)
		artist = qs(0xfdfbde3a)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = female
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 226
		album_title = qs(0x73025c91)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC131 = {
		checksum = DLC131
		name = 'DLC131'
		Title = qs(0x19e0f58e)
		artist = qs(0x69439c8b)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 227
		album_title = qs(0x69c8c721)
		guitar_difficulty_rating = 2
		bass_difficulty_rating = 1
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 2
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC132 = {
		checksum = DLC132
		name = 'DLC132'
		Title = qs(0x94b46d7b)
		artist = qs(0x39a96446)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 252
		album_title = qs(0xe30397fe)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC139 = {
		checksum = DLC139
		name = 'DLC139'
		Title = qs(0x3da89cf7)
		artist = qs(0xd80eb4f9)
		year = 2003
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 191
		album_title = qs(0x3da89cf7)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC140 = {
		checksum = DLC140
		name = 'DLC140'
		Title = qs(0xd3a7cdf1)
		artist = qs(0x27760cf0)
		year = 1989
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 351
		album_title = qs(0xc0dbfe8e)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 2
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 0
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 0
	}
	DLC141 = {
		checksum = DLC141
		name = 'DLC141'
		Title = qs(0x8d8c96a1)
		artist = qs(0xad8d4c56)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Pop	Punk`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 176
		album_title = qs(0x8d8c96a1)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC136 = {
		checksum = DLC136
		name = 'DLC136'
		Title = qs(0xa677348f)
		artist = qs(0xf5a8bb50)
		year = 1995
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 159
		album_title = qs(0x7c3fe064)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 0
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 0
	}
	DLC137 = {
		checksum = DLC137
		name = 'DLC137'
		Title = qs(0x49c18029)
		artist = qs(0x05c3ff42)
		year = 1994
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 128
		album_title = qs(0x12404d0f)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 7
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC138 = {
		checksum = DLC138
		name = 'DLC138'
		Title = qs(0x021e0136)
		artist = qs(0x05c2ca6d)
		year = 2004
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 174
		album_title = qs(0x6328c49d)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 3
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC142 = {
		checksum = DLC142
		name = 'DLC142'
		Title = qs(0x95e42173)
		artist = qs(0x17465efc)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Nu	Metal`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		double_kick = 1
		Duration = 245
		album_title = qs(0x0bf7e8cb)
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 8
		vocals_difficulty_rating = 9
		drums_difficulty_rating = 9
		band_difficulty_rating = 9
		overall_song_volume = 0
	}
	DLC143 = {
		checksum = DLC143
		name = 'DLC143'
		Title = qs(0x4b2d0041)
		artist = qs(0x63a4aa9e)
		year = 2005
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 155
		album_title = qs(0x1340b33f)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 8
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC144 = {
		checksum = DLC144
		name = 'DLC144'
		Title = qs(0x83ce97fc)
		artist = qs(0x0293b7b8)
		year = 2007
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = Punk
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 217
		album_title = qs(0x83ce97fc)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 1
		drums_difficulty_rating = 6
		band_difficulty_rating = 3
		overall_song_volume = 0
	}
	DLC148 = {
		checksum = DLC148
		name = 'DLC148'
		Title = qs(0x19a92501)
		artist = qs(0xb2b64e39)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 190
		album_title = qs(0x1e4646f4)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 6
		band_difficulty_rating = 5
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 0
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 0
	}
	DLC149 = {
		checksum = DLC149
		name = 'DLC149'
		Title = qs(0xd5753c75)
		artist = qs(0xb2b64e39)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 257
		album_title = qs(0x1e4646f4)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC150 = {
		checksum = DLC150
		name = 'DLC150'
		Title = qs(0xd24b5be9)
		artist = qs(0xb2b64e39)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 187
		album_title = qs(0x1e4646f4)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 9
		drums_difficulty_rating = 3
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC151 = {
		checksum = DLC151
		name = 'DLC151'
		Title = qs(0x811b4ec6)
		artist = qs(0xe28db056)
		year = 2008
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 277
		album_title = qs(0x53b132ed)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 3
		vocals_difficulty_rating = 6
		drums_difficulty_rating = 3
		band_difficulty_rating = 4
		overall_song_volume = 0
	}
	DLC152 = {
		checksum = DLC152
		name = 'DLC152'
		Title = qs(0x68f6acc4)
		artist = qs(0xe28db056)
		year = 2006
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 202
		album_title = qs(0x50bf1fdb)
		guitar_difficulty_rating = 3
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 2
		band_difficulty_rating = 4
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC153 = {
		checksum = DLC153
		name = 'DLC153'
		Title = qs(0x6a51debc)
		artist = qs(0xe28db056)
		year = 2004
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 173
		album_title = qs(0x2ced7545)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 1
		band_difficulty_rating = 5
		overall_song_volume = 0
	}
	DLC134 = {
		checksum = DLC134
		name = 'DLC134'
		Title = qs(0x50d85403)
		artist = qs(0x9933ce56)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 243
		album_title = qs(0xd3682b6d)
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 4
		band_difficulty_rating = 4
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC133 = {
		checksum = DLC133
		name = 'DLC133'
		Title = qs(0xffc1df0a)
		artist = qs(0x801820e2)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Nu	Metal`
		double_kick = 1
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 214
		album_title = qs(0xf4ff8918)
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 4
		drums_difficulty_rating = 5
		band_difficulty_rating = 4
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 120
	}
	DLC135 = {
		checksum = DLC135
		name = 'DLC135'
		Title = qs(0xc15fa9c8)
		artist = qs(0x364f13bf)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = alternative
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		Duration = 188
		album_title = qs(0x7c7d2c53)
		guitar_difficulty_rating = 8
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 3
		drums_difficulty_rating = 7
		band_difficulty_rating = 6
		overall_song_volume = 0
	}
	DLC154 = {
		checksum = DLC154
		name = 'DLC154'
		Title = qs(0xb735b12a)
		artist = qs(0xa46768f8)
		year = 1996
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = None
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 7
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 9
		band_difficulty_rating = 6
	}
	DLC155 = {
		checksum = DLC155
		name = 'DLC155'
		Title = qs(0xe88c601e)
		artist = qs(0x1aa9e35d)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Nu	Metal`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 5
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 8
		band_difficulty_rating = 5
	}
	DLC156 = {
		checksum = DLC156
		name = 'DLC156'
		Title = qs(0xab98c114)
		artist = qs(0x64d28dad)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 8
		band_difficulty_rating = 5
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 120
	}
	DLC157 = {
		checksum = DLC157
		name = 'DLC157'
		Title = qs(0x910ade06)
		artist = qs(0x3d3d9d71)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		double_kick = 1
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
	}
	DLC162 = {
		checksum = DLC162
		name = 'DLC162'
		Title = qs(0x9198389b)
		artist = qs(0xeccb3fa1)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 4
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 8
		drums_difficulty_rating = 8
		band_difficulty_rating = 6
		thin_fretbar_8note_params_low_bpm = 0
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 0
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC163 = {
		checksum = DLC163
		name = 'DLC163'
		Title = qs(0xb33a15e7)
		artist = qs(0x21d4b200)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		double_kick = 1
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 7
		bass_difficulty_rating = 6
		vocals_difficulty_rating = 5
		drums_difficulty_rating = 8
		band_difficulty_rating = 7
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 1
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
	DLC164 = {
		checksum = DLC164
		name = 'DLC164'
		Title = qs(0x1f9a6c96)
		artist = qs(0x064c5764)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = rock
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		overall_song_volume = 0
		Duration = 268
		guitar_difficulty_rating = 6
		bass_difficulty_rating = 5
		vocals_difficulty_rating = 7
		drums_difficulty_rating = 6
		band_difficulty_rating = 6
	}
	DLC161 = {
		checksum = DLC161
		name = 'DLC161'
		Title = qs(0xd4a31ec3)
		artist = qs(0x29b7a45a)
		year = 2009
		artist_text = $artist_text_by
		original_artist = 1
		leaderboard = 1
		singer = male
		genre = `Blues	Rock`
		countoff = 'sticks_normal'
		drum_kit = 'classicrock'
		double_kick = 1
		Duration = 268
		guitar_difficulty_rating = 9
		bass_difficulty_rating = 4
		vocals_difficulty_rating = 0
		drums_difficulty_rating = 9
		band_difficulty_rating = 7
		album_title = qs(0x47cc6adf)
		overall_song_volume = 0
		thin_fretbar_8note_params_low_bpm = 1
		thin_fretbar_8note_params_high_bpm = 200
		thin_fretbar_16note_params_low_bpm = 1
		thin_fretbar_16note_params_high_bpm = 1
	}
}
